// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// BillingUsageRequestBuilder builds and executes requests for operations under \v1\billing\usage
type BillingUsageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
//
type BillingUsageRequestBuilderGetQueryParameters struct {
    // Filter to specific dim; omit for all dims
    Dim *string "uriparametername:\"dim\""
    // When true, return only metered (billable) usage dims.
    Metered_only *bool "uriparametername:\"metered_only\""
    // Start of usage window (timestamp; default: billing period start).
    Since *string "uriparametername:\"since\""
    // End of usage window (timestamp; default: now).
    Until *string "uriparametername:\"until\""
    // Optional workspace override (admin only); defaults to tenant workspace
    Workspace_id *string "uriparametername:\"workspace_id\""
}
// BillingUsageRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type BillingUsageRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *BillingUsageRequestBuilderGetQueryParameters
}
// NewBillingUsageRequestBuilderInternal instantiates a new BillingUsageRequestBuilder and sets the default values.
func NewBillingUsageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*BillingUsageRequestBuilder) {
    m := &BillingUsageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/billing/usage{?dim*,metered_only*,since*,until*,workspace_id*}", pathParameters),
    }
    return m
}
// NewBillingUsageRequestBuilder instantiates a new BillingUsageRequestBuilder and sets the default values.
func NewBillingUsageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*BillingUsageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewBillingUsageRequestBuilderInternal(urlParams, requestAdapter)
}
//
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *BillingUsageRequestBuilder) Get(ctx context.Context, requestConfiguration *BillingUsageRequestBuilderGetRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
//
// returns a *RequestInformation when successful
func (m *BillingUsageRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *BillingUsageRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *BillingUsageRequestBuilder when successful
func (m *BillingUsageRequestBuilder) WithUrl(rawUrl string)(*BillingUsageRequestBuilder) {
    return NewBillingUsageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
