// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CdpFrameRequestBuilder builds and executes requests for operations under \v1\cdp\frame
type CdpFrameRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CdpFrameRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CdpFrameRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCdpFrameRequestBuilderInternal instantiates a new CdpFrameRequestBuilder and sets the default values.
func NewCdpFrameRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CdpFrameRequestBuilder) {
    m := &CdpFrameRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/cdp/frame", pathParameters),
    }
    return m
}
// NewCdpFrameRequestBuilder instantiates a new CdpFrameRequestBuilder and sets the default values.
func NewCdpFrameRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CdpFrameRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCdpFrameRequestBuilderInternal(urlParams, requestAdapter)
}
// Post engine-agnostic live-view frame capture (cross-engine). Returns a single base64-encoded JPEG frame of a live interactive session,using the same capture path across Chromium, Firefox, and WebKit. Gating: 1. Tenant authentication 2. Revocation check 3. Tier gate (paid plan required, free denied, pro+/trial allowed), checked before ownership 4. Session ownership (the session must belong to the authenticated organisation)Returns 200 {"format":"jpeg","data":"<base64>","engine","width","height"} on success;403 cdp_not_enabled (tier) / cdp_revoked; 404 session_not_found; 502 frame_failed.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *CdpFrameRequestBuilder) Post(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CdpFrameRequestable, requestConfiguration *CdpFrameRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPostRequestInformation engine-agnostic live-view frame capture (cross-engine). Returns a single base64-encoded JPEG frame of a live interactive session,using the same capture path across Chromium, Firefox, and WebKit. Gating: 1. Tenant authentication 2. Revocation check 3. Tier gate (paid plan required, free denied, pro+/trial allowed), checked before ownership 4. Session ownership (the session must belong to the authenticated organisation)Returns 200 {"format":"jpeg","data":"<base64>","engine","width","height"} on success;403 cdp_not_enabled (tier) / cdp_revoked; 404 session_not_found; 502 frame_failed.
// returns a *RequestInformation when successful
func (m *CdpFrameRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CdpFrameRequestable, requestConfiguration *CdpFrameRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CdpFrameRequestBuilder when successful
func (m *CdpFrameRequestBuilder) WithUrl(rawUrl string)(*CdpFrameRequestBuilder) {
    return NewCdpFrameRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
