// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use MeExportGetResponseable instead.
type MeExportResponse struct {
    MeExportGetResponse
}
// NewMeExportResponse instantiates a new MeExportResponse and sets the default values.
func NewMeExportResponse()(*MeExportResponse) {
    m := &MeExportResponse{
        MeExportGetResponse: *NewMeExportGetResponse(),
    }
    return m
}
// CreateMeExportResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMeExportResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMeExportResponse(), nil
}
// Deprecated: This class is obsolete. Use MeExportGetResponseable instead.
type MeExportResponseable interface {
    MeExportGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
