// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i0c56bda45ac40453d1fad1eb4f4bc55da68ce491845ad7c78e1fccf7516ffdae "github.com/GhostCrawl/ghostcrawl-go/v2/v1/me/usage"
)

// MeUsageRequestBuilder builds and executes requests for operations under \v1\me\usage
type MeUsageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// MeUsageRequestBuilderGetQueryParameters return cost/usage report scoped strictly to caller's primary_team_id.
type MeUsageRequestBuilderGetQueryParameters struct {
    // Deprecated: This property is deprecated, use PeriodAsGetPeriodQueryParameterType instead
    Period *string "uriparametername:\"period\""
    PeriodAsGetPeriodQueryParameterType *i0c56bda45ac40453d1fad1eb4f4bc55da68ce491845ad7c78e1fccf7516ffdae.GetPeriodQueryParameterType "uriparametername:\"period\""
}
// MeUsageRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type MeUsageRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *MeUsageRequestBuilderGetQueryParameters
}
// NewMeUsageRequestBuilderInternal instantiates a new MeUsageRequestBuilder and sets the default values.
func NewMeUsageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MeUsageRequestBuilder) {
    m := &MeUsageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/me/usage{?period*}", pathParameters),
    }
    return m
}
// NewMeUsageRequestBuilder instantiates a new MeUsageRequestBuilder and sets the default values.
func NewMeUsageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*MeUsageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewMeUsageRequestBuilderInternal(urlParams, requestAdapter)
}
// Get return cost/usage report scoped strictly to caller's primary_team_id.
// Deprecated: This method is obsolete. Use GetAsUsageGetResponse instead.
// returns a MeUsageResponseable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *MeUsageRequestBuilder) Get(ctx context.Context, requestConfiguration *MeUsageRequestBuilderGetRequestConfiguration)(MeUsageResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateMeUsageResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(MeUsageResponseable), nil
}
// GetAsUsageGetResponse return cost/usage report scoped strictly to caller's primary_team_id.
// returns a MeUsageGetResponseable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *MeUsageRequestBuilder) GetAsUsageGetResponse(ctx context.Context, requestConfiguration *MeUsageRequestBuilderGetRequestConfiguration)(MeUsageGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateMeUsageGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(MeUsageGetResponseable), nil
}
// ToGetRequestInformation return cost/usage report scoped strictly to caller's primary_team_id.
// returns a *RequestInformation when successful
func (m *MeUsageRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *MeUsageRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MeUsageRequestBuilder when successful
func (m *MeUsageRequestBuilder) WithUrl(rawUrl string)(*MeUsageRequestBuilder) {
    return NewMeUsageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
