// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// QueuesItemPopRequestBuilder builds and executes requests for operations under \v1\queues\{name}\pop
type QueuesItemPopRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// QueuesItemPopRequestBuilderGetQueryParameters gET /v1/queues/{name}/pop?count=N, read up to N items from the queue. Returns {items: [{id, url, meta}]}. Empty list when nothing available.
type QueuesItemPopRequestBuilderGetQueryParameters struct {
    Count *int32 "uriparametername:\"count\""
}
// QueuesItemPopRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type QueuesItemPopRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *QueuesItemPopRequestBuilderGetQueryParameters
}
// NewQueuesItemPopRequestBuilderInternal instantiates a new QueuesItemPopRequestBuilder and sets the default values.
func NewQueuesItemPopRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*QueuesItemPopRequestBuilder) {
    m := &QueuesItemPopRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/queues/{name}/pop{?count*}", pathParameters),
    }
    return m
}
// NewQueuesItemPopRequestBuilder instantiates a new QueuesItemPopRequestBuilder and sets the default values.
func NewQueuesItemPopRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*QueuesItemPopRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewQueuesItemPopRequestBuilderInternal(urlParams, requestAdapter)
}
// Get gET /v1/queues/{name}/pop?count=N, read up to N items from the queue. Returns {items: [{id, url, meta}]}. Empty list when nothing available.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *QueuesItemPopRequestBuilder) Get(ctx context.Context, requestConfiguration *QueuesItemPopRequestBuilderGetRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToGetRequestInformation gET /v1/queues/{name}/pop?count=N, read up to N items from the queue. Returns {items: [{id, url, meta}]}. Empty list when nothing available.
// returns a *RequestInformation when successful
func (m *QueuesItemPopRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *QueuesItemPopRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *QueuesItemPopRequestBuilder when successful
func (m *QueuesItemPopRequestBuilder) WithUrl(rawUrl string)(*QueuesItemPopRequestBuilder) {
    return NewQueuesItemPopRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
