// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// QueuesItemPushRequestBuilder builds and executes requests for operations under \v1\queues\{name}\push
type QueuesItemPushRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// QueuesItemPushRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type QueuesItemPushRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewQueuesItemPushRequestBuilderInternal instantiates a new QueuesItemPushRequestBuilder and sets the default values.
func NewQueuesItemPushRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*QueuesItemPushRequestBuilder) {
    m := &QueuesItemPushRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/queues/{name}/push", pathParameters),
    }
    return m
}
// NewQueuesItemPushRequestBuilder instantiates a new QueuesItemPushRequestBuilder and sets the default values.
func NewQueuesItemPushRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*QueuesItemPushRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewQueuesItemPushRequestBuilderInternal(urlParams, requestAdapter)
}
// Post pOST /v1/queues/{name}/push, enqueue URLs. Body: {"urls": [.], "dedup"?: true}Returns {added: N}. 429 when queue cap exceeded.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *QueuesItemPushRequestBuilder) Post(ctx context.Context, body QueuesItemPushPostRequestBodyable, requestConfiguration *QueuesItemPushRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPostRequestInformation pOST /v1/queues/{name}/push, enqueue URLs. Body: {"urls": [.], "dedup"?: true}Returns {added: N}. 429 when queue cap exceeded.
// returns a *RequestInformation when successful
func (m *QueuesItemPushRequestBuilder) ToPostRequestInformation(ctx context.Context, body QueuesItemPushPostRequestBodyable, requestConfiguration *QueuesItemPushRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *QueuesItemPushRequestBuilder when successful
func (m *QueuesItemPushRequestBuilder) WithUrl(rawUrl string)(*QueuesItemPushRequestBuilder) {
    return NewQueuesItemPushRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
