// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// RecordingsRequestBuilder builds and executes requests for operations under \v1\recordings
type RecordingsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// RecordingsRequestBuilderGetQueryParameters gET /v1/recordings, cursor pagination. response gains total_count (additive); items[*] shape unchanged. owner_id filter requires recordings:admin scope to be honored; without it, the filter is silently dropped (not 403). created_at_from > created_at_to → 400 (not 422). tier gate NOT applied at list layer.
type RecordingsRequestBuilderGetQueryParameters struct {
    Created_at_from *string "uriparametername:\"created_at_from\""
    Created_at_to *string "uriparametername:\"created_at_to\""
    Cursor *string "uriparametername:\"cursor\""
    Limit *int32 "uriparametername:\"limit\""
    Owner_id *string "uriparametername:\"owner_id\""
    Tags *string "uriparametername:\"tags\""
}
// RecordingsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type RecordingsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *RecordingsRequestBuilderGetQueryParameters
}
// ByRecording_Id gets an item from the ghostcrawl.v1.recordings.item collection
// returns a *RecordingsRecording_ItemRequestBuilder when successful
func (m *RecordingsRequestBuilder) ByRecording_Id(recording_Id string)(*RecordingsRecording_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if recording_Id != "" {
        urlTplParams["recording_%2Did"] = recording_Id
    }
    return NewRecordingsRecording_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewRecordingsRequestBuilderInternal instantiates a new RecordingsRequestBuilder and sets the default values.
func NewRecordingsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RecordingsRequestBuilder) {
    m := &RecordingsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/recordings{?created_at_from*,created_at_to*,cursor*,limit*,owner_id*,tags*}", pathParameters),
    }
    return m
}
// NewRecordingsRequestBuilder instantiates a new RecordingsRequestBuilder and sets the default values.
func NewRecordingsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*RecordingsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewRecordingsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get gET /v1/recordings, cursor pagination. response gains total_count (additive); items[*] shape unchanged. owner_id filter requires recordings:admin scope to be honored; without it, the filter is silently dropped (not 403). created_at_from > created_at_to → 400 (not 422). tier gate NOT applied at list layer.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *RecordingsRequestBuilder) Get(ctx context.Context, requestConfiguration *RecordingsRequestBuilderGetRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToGetRequestInformation gET /v1/recordings, cursor pagination. response gains total_count (additive); items[*] shape unchanged. owner_id filter requires recordings:admin scope to be honored; without it, the filter is silently dropped (not 403). created_at_from > created_at_to → 400 (not 422). tier gate NOT applied at list layer.
// returns a *RequestInformation when successful
func (m *RecordingsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *RecordingsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *RecordingsRequestBuilder when successful
func (m *RecordingsRequestBuilder) WithUrl(rawUrl string)(*RecordingsRequestBuilder) {
    return NewRecordingsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
