// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SchedulesRequestBuilder builds and executes requests for operations under \v1\schedules
type SchedulesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SchedulesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SchedulesRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// SchedulesRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SchedulesRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// BySchedule_id gets an item from the ghostcrawl.v1.schedules.item collection
// returns a *SchedulesWithSchedule_ItemRequestBuilder when successful
func (m *SchedulesRequestBuilder) BySchedule_id(schedule_id string)(*SchedulesWithSchedule_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if schedule_id != "" {
        urlTplParams["schedule_id"] = schedule_id
    }
    return NewSchedulesWithSchedule_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewSchedulesRequestBuilderInternal instantiates a new SchedulesRequestBuilder and sets the default values.
func NewSchedulesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SchedulesRequestBuilder) {
    m := &SchedulesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/schedules", pathParameters),
    }
    return m
}
// NewSchedulesRequestBuilder instantiates a new SchedulesRequestBuilder and sets the default values.
func NewSchedulesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SchedulesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSchedulesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get gET /v1/schedules, list.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *SchedulesRequestBuilder) Get(ctx context.Context, requestConfiguration *SchedulesRequestBuilderGetRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// Post pOST /v1/schedules, create a cron-triggered scrape/crawl schedule. Validations:- schedule:write scope required (403 forbidden_scope on miss)- cron_expr must parse (422 invalid_cron)- job_type must be 'scrape', 'crawl', or 'change_monitor' (422 invalid_job_type)- notify_webhook must be SSRF-safe HTTPS URL if provided (422 invalid_webhook)- per-org count < cap (429 schedule_cap_reached)- unique name per org (409 schedule_exists)
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *SchedulesRequestBuilder) Post(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.ScheduleCreateRequestable, requestConfiguration *SchedulesRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToGetRequestInformation gET /v1/schedules, list.
// returns a *RequestInformation when successful
func (m *SchedulesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SchedulesRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPostRequestInformation pOST /v1/schedules, create a cron-triggered scrape/crawl schedule. Validations:- schedule:write scope required (403 forbidden_scope on miss)- cron_expr must parse (422 invalid_cron)- job_type must be 'scrape', 'crawl', or 'change_monitor' (422 invalid_job_type)- notify_webhook must be SSRF-safe HTTPS URL if provided (422 invalid_webhook)- per-org count < cap (429 schedule_cap_reached)- unique name per org (409 schedule_exists)
// returns a *RequestInformation when successful
func (m *SchedulesRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.ScheduleCreateRequestable, requestConfiguration *SchedulesRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SchedulesRequestBuilder when successful
func (m *SchedulesRequestBuilder) WithUrl(rawUrl string)(*SchedulesRequestBuilder) {
    return NewSchedulesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
