// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
)

// SelfhostByoBehaviorRequestBuilder builds and executes requests for operations under \v1\selfhost\byo\behavior
type SelfhostByoBehaviorRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SelfhostByoBehaviorRequestBuilderPutRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SelfhostByoBehaviorRequestBuilderPutRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewSelfhostByoBehaviorRequestBuilderInternal instantiates a new SelfhostByoBehaviorRequestBuilder and sets the default values.
func NewSelfhostByoBehaviorRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SelfhostByoBehaviorRequestBuilder) {
    m := &SelfhostByoBehaviorRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/selfhost/byo/behavior", pathParameters),
    }
    return m
}
// NewSelfhostByoBehaviorRequestBuilder instantiates a new SelfhostByoBehaviorRequestBuilder and sets the default values.
func NewSelfhostByoBehaviorRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SelfhostByoBehaviorRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSelfhostByoBehaviorRequestBuilderInternal(urlParams, requestAdapter)
}
// Put **Self-host deployments only.** Validate + persist a BYO behavior JSON, then report the sanitized count. Contract: ``{"human_actions": [ {kind,.},. ]}``. ``human_actions`` MUST be a list; it is passed through byo_behavior.sanitize_actions (allow-list + clamp). A non-empty input that sanitizes to an EMPTY plan (every action an invalid kind) → 422 invalid_behavior_json (nothing valid to apply). Success → write ~/.ghostcrawl/behavior.json + {reloaded, actions}.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *SelfhostByoBehaviorRequestBuilder) Put(ctx context.Context, body SelfhostByoBehaviorPutRequestBodyable, requestConfiguration *SelfhostByoBehaviorRequestBuilderPutRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPutRequestInformation **Self-host deployments only.** Validate + persist a BYO behavior JSON, then report the sanitized count. Contract: ``{"human_actions": [ {kind,.},. ]}``. ``human_actions`` MUST be a list; it is passed through byo_behavior.sanitize_actions (allow-list + clamp). A non-empty input that sanitizes to an EMPTY plan (every action an invalid kind) → 422 invalid_behavior_json (nothing valid to apply). Success → write ~/.ghostcrawl/behavior.json + {reloaded, actions}.
// returns a *RequestInformation when successful
func (m *SelfhostByoBehaviorRequestBuilder) ToPutRequestInformation(ctx context.Context, body SelfhostByoBehaviorPutRequestBodyable, requestConfiguration *SelfhostByoBehaviorRequestBuilderPutRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PUT, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SelfhostByoBehaviorRequestBuilder when successful
func (m *SelfhostByoBehaviorRequestBuilder) WithUrl(rawUrl string)(*SelfhostByoBehaviorRequestBuilder) {
    return NewSelfhostByoBehaviorRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
