// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SessionsItemTakeoverRequestBuilder builds and executes requests for operations under \v1\sessions\{profile_-id}\takeover
type SessionsItemTakeoverRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SessionsItemTakeoverRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SessionsItemTakeoverRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewSessionsItemTakeoverRequestBuilderInternal instantiates a new SessionsItemTakeoverRequestBuilder and sets the default values.
func NewSessionsItemTakeoverRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SessionsItemTakeoverRequestBuilder) {
    m := &SessionsItemTakeoverRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/sessions/{profile_%2Did}/takeover", pathParameters),
    }
    return m
}
// NewSessionsItemTakeoverRequestBuilder instantiates a new SessionsItemTakeoverRequestBuilder and sets the default values.
func NewSessionsItemTakeoverRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SessionsItemTakeoverRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSessionsItemTakeoverRequestBuilderInternal(urlParams, requestAdapter)
}
// Post action-dispatch shim for the takeover surface (Surface L acceptance test). POST /v1/sessions/{id}/takeover with {"action": "mint"} delegates to theHMAC-token mint logic (same as /takeover_token). {"action": "release"}delegates to the control flag release logic (same as /takeover_release). This endpoint exists because the Surface L live test uses a single URLwith an action discriminator, while the underlying REST surface exposestwo dedicated sub-paths. Both entry points share identical auth, tier,and cross-tenant guards.
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *SessionsItemTakeoverRequestBuilder) Post(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.TakeoverActionBodyable, requestConfiguration *SessionsItemTakeoverRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPostRequestInformation action-dispatch shim for the takeover surface (Surface L acceptance test). POST /v1/sessions/{id}/takeover with {"action": "mint"} delegates to theHMAC-token mint logic (same as /takeover_token). {"action": "release"}delegates to the control flag release logic (same as /takeover_release). This endpoint exists because the Surface L live test uses a single URLwith an action discriminator, while the underlying REST surface exposestwo dedicated sub-paths. Both entry points share identical auth, tier,and cross-tenant guards.
// returns a *RequestInformation when successful
func (m *SessionsItemTakeoverRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.TakeoverActionBodyable, requestConfiguration *SessionsItemTakeoverRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SessionsItemTakeoverRequestBuilder when successful
func (m *SessionsItemTakeoverRequestBuilder) WithUrl(rawUrl string)(*SessionsItemTakeoverRequestBuilder) {
    return NewSessionsItemTakeoverRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
