// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// StorageStatesItemAttachRequestBuilder builds and executes requests for operations under \v1\storage-states\{id_or_name}\attach
type StorageStatesItemAttachRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// StorageStatesItemAttachRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type StorageStatesItemAttachRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewStorageStatesItemAttachRequestBuilderInternal instantiates a new StorageStatesItemAttachRequestBuilder and sets the default values.
func NewStorageStatesItemAttachRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StorageStatesItemAttachRequestBuilder) {
    m := &StorageStatesItemAttachRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/storage-states/{id_or_name}/attach", pathParameters),
    }
    return m
}
// NewStorageStatesItemAttachRequestBuilder instantiates a new StorageStatesItemAttachRequestBuilder and sets the default values.
func NewStorageStatesItemAttachRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StorageStatesItemAttachRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewStorageStatesItemAttachRequestBuilderInternal(urlParams, requestAdapter)
}
// Post pOST /v1/storage-states/{id_or_name}/attach, attach a storage state to a profile. Decrypts and validates the named storage state, filters expired cookies,then sets the sticky binding so subsequent sessions on this profile startwith the saved state loaded. Cross-tenant miss → storage_state_not_found (404, not 403; enumeration guard). Corrupted data → storage_state_decrypt_failed (400).
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *StorageStatesItemAttachRequestBuilder) Post(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.StorageStateAttachRequestable, requestConfiguration *StorageStatesItemAttachRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPostRequestInformation pOST /v1/storage-states/{id_or_name}/attach, attach a storage state to a profile. Decrypts and validates the named storage state, filters expired cookies,then sets the sticky binding so subsequent sessions on this profile startwith the saved state loaded. Cross-tenant miss → storage_state_not_found (404, not 403; enumeration guard). Corrupted data → storage_state_decrypt_failed (400).
// returns a *RequestInformation when successful
func (m *StorageStatesItemAttachRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia85961cb4accefe00a2a455d3f94d1a3e468380689dbe1efc71d3936b800cb60.StorageStateAttachRequestable, requestConfiguration *StorageStatesItemAttachRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *StorageStatesItemAttachRequestBuilder when successful
func (m *StorageStatesItemAttachRequestBuilder) WithUrl(rawUrl string)(*StorageStatesItemAttachRequestBuilder) {
    return NewStorageStatesItemAttachRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
