// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
)

// WebhooksItemDeliveriesItemRetryRequestBuilder builds and executes requests for operations under \v1\webhooks\{webhook_id}\deliveries\{delivery_id}\retry
type WebhooksItemDeliveriesItemRetryRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WebhooksItemDeliveriesItemRetryRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WebhooksItemDeliveriesItemRetryRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWebhooksItemDeliveriesItemRetryRequestBuilderInternal instantiates a new WebhooksItemDeliveriesItemRetryRequestBuilder and sets the default values.
func NewWebhooksItemDeliveriesItemRetryRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksItemDeliveriesItemRetryRequestBuilder) {
    m := &WebhooksItemDeliveriesItemRetryRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry", pathParameters),
    }
    return m
}
// NewWebhooksItemDeliveriesItemRetryRequestBuilder instantiates a new WebhooksItemDeliveriesItemRetryRequestBuilder and sets the default values.
func NewWebhooksItemDeliveriesItemRetryRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksItemDeliveriesItemRetryRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWebhooksItemDeliveriesItemRetryRequestBuilderInternal(urlParams, requestAdapter)
}
// Post pOST /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry. Re-enqueues the failed delivery with a fresh delivery_id; the original event_id is preserved so downstream consumers can detect the retry.
// returns a RetryDeliveryResponseable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *WebhooksItemDeliveriesItemRetryRequestBuilder) Post(ctx context.Context, requestConfiguration *WebhooksItemDeliveriesItemRetryRequestBuilderPostRequestConfiguration)(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.RetryDeliveryResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateRetryDeliveryResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.RetryDeliveryResponseable), nil
}
// ToPostRequestInformation pOST /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry. Re-enqueues the failed delivery with a fresh delivery_id; the original event_id is preserved so downstream consumers can detect the retry.
// returns a *RequestInformation when successful
func (m *WebhooksItemDeliveriesItemRetryRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *WebhooksItemDeliveriesItemRetryRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *WebhooksItemDeliveriesItemRetryRequestBuilder when successful
func (m *WebhooksItemDeliveriesItemRetryRequestBuilder) WithUrl(rawUrl string)(*WebhooksItemDeliveriesItemRetryRequestBuilder) {
    return NewWebhooksItemDeliveriesItemRetryRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
