// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
)

// SessionsItemRecordingStartRequestBuilder builds and executes requests for operations under \v1\sessions\{profile_-id}\recording\start
type SessionsItemRecordingStartRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SessionsItemRecordingStartRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SessionsItemRecordingStartRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewSessionsItemRecordingStartRequestBuilderInternal instantiates a new SessionsItemRecordingStartRequestBuilder and sets the default values.
func NewSessionsItemRecordingStartRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SessionsItemRecordingStartRequestBuilder) {
    m := &SessionsItemRecordingStartRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/sessions/{profile_%2Did}/recording/start", pathParameters),
    }
    return m
}
// NewSessionsItemRecordingStartRequestBuilder instantiates a new SessionsItemRecordingStartRequestBuilder and sets the default values.
func NewSessionsItemRecordingStartRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SessionsItemRecordingStartRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSessionsItemRecordingStartRequestBuilderInternal(urlParams, requestAdapter)
}
// Post pOST /v1/sessions/{profile_id}/recording/start. Tier: interaction (recording_enabled on org). Returns 201 RecordingResponse;
// returns a UntypedNodeable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *SessionsItemRecordingStartRequestBuilder) Post(ctx context.Context, requestConfiguration *SessionsItemRecordingStartRequestBuilderPostRequestConfiguration)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// ToPostRequestInformation pOST /v1/sessions/{profile_id}/recording/start. Tier: interaction (recording_enabled on org). Returns 201 RecordingResponse;
// returns a *RequestInformation when successful
func (m *SessionsItemRecordingStartRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *SessionsItemRecordingStartRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SessionsItemRecordingStartRequestBuilder when successful
func (m *SessionsItemRecordingStartRequestBuilder) WithUrl(rawUrl string)(*SessionsItemRecordingStartRequestBuilder) {
    return NewSessionsItemRecordingStartRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
