// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
)

// WebhooksItemRotateSecretRequestBuilder builds and executes requests for operations under \v1\webhooks\{webhook_id}\rotate-secret
type WebhooksItemRotateSecretRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WebhooksItemRotateSecretRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WebhooksItemRotateSecretRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWebhooksItemRotateSecretRequestBuilderInternal instantiates a new WebhooksItemRotateSecretRequestBuilder and sets the default values.
func NewWebhooksItemRotateSecretRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksItemRotateSecretRequestBuilder) {
    m := &WebhooksItemRotateSecretRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/webhooks/{webhook_id}/rotate-secret", pathParameters),
    }
    return m
}
// NewWebhooksItemRotateSecretRequestBuilder instantiates a new WebhooksItemRotateSecretRequestBuilder and sets the default values.
func NewWebhooksItemRotateSecretRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksItemRotateSecretRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWebhooksItemRotateSecretRequestBuilderInternal(urlParams, requestAdapter)
}
// Post pOST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains valid for a short grace period so in-flight deliveries can still be verified.
// returns a RotateSecretResponseable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *WebhooksItemRotateSecretRequestBuilder) Post(ctx context.Context, requestConfiguration *WebhooksItemRotateSecretRequestBuilderPostRequestConfiguration)(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.RotateSecretResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateRotateSecretResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.RotateSecretResponseable), nil
}
// ToPostRequestInformation pOST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains valid for a short grace period so in-flight deliveries can still be verified.
// returns a *RequestInformation when successful
func (m *WebhooksItemRotateSecretRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *WebhooksItemRotateSecretRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *WebhooksItemRotateSecretRequestBuilder when successful
func (m *WebhooksItemRotateSecretRequestBuilder) WithUrl(rawUrl string)(*WebhooksItemRotateSecretRequestBuilder) {
    return NewWebhooksItemRotateSecretRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
