// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739 "github.com/GhostCrawl/ghostcrawl-go/v2/models"
)

// WebhooksWithWebhook_ItemRequestBuilder builds and executes requests for operations under \v1\webhooks\{webhook_id}
type WebhooksWithWebhook_ItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WebhooksWithWebhook_ItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WebhooksWithWebhook_ItemRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// WebhooksWithWebhook_ItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WebhooksWithWebhook_ItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWebhooksWithWebhook_ItemRequestBuilderInternal instantiates a new WebhooksWithWebhook_ItemRequestBuilder and sets the default values.
func NewWebhooksWithWebhook_ItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksWithWebhook_ItemRequestBuilder) {
    m := &WebhooksWithWebhook_ItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/webhooks/{webhook_id}", pathParameters),
    }
    return m
}
// NewWebhooksWithWebhook_ItemRequestBuilder instantiates a new WebhooksWithWebhook_ItemRequestBuilder and sets the default values.
func NewWebhooksWithWebhook_ItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WebhooksWithWebhook_ItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWebhooksWithWebhook_ItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete dELETE /v1/webhooks/{webhook_id}. secret keys deleted best-effort.
// returns a ProblemDetails error when the service returns a 422 status code
func (m *WebhooksWithWebhook_ItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *WebhooksWithWebhook_ItemRequestBuilderDeleteRequestConfiguration)(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// Deliveries the deliveries property
// returns a *WebhooksItemDeliveriesRequestBuilder when successful
func (m *WebhooksWithWebhook_ItemRequestBuilder) Deliveries()(*WebhooksItemDeliveriesRequestBuilder) {
    return NewWebhooksItemDeliveriesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Get secret: NOT returned.
// returns a WebhookPublicable when successful
// returns a ProblemDetails error when the service returns a 422 status code
func (m *WebhooksWithWebhook_ItemRequestBuilder) Get(ctx context.Context, requestConfiguration *WebhooksWithWebhook_ItemRequestBuilderGetRequestConfiguration)(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.WebhookPublicable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "422": ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateProblemDetailsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.CreateWebhookPublicFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ib5cfef42d548d9daa383ff1f301f0dd73d527176adc637b33779039e2d129739.WebhookPublicable), nil
}
// RotateSecret the rotateSecret property
// returns a *WebhooksItemRotateSecretRequestBuilder when successful
func (m *WebhooksWithWebhook_ItemRequestBuilder) RotateSecret()(*WebhooksItemRotateSecretRequestBuilder) {
    return NewWebhooksItemRotateSecretRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToDeleteRequestInformation dELETE /v1/webhooks/{webhook_id}. secret keys deleted best-effort.
// returns a *RequestInformation when successful
func (m *WebhooksWithWebhook_ItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *WebhooksWithWebhook_ItemRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/problem+json")
    return requestInfo, nil
}
// ToGetRequestInformation secret: NOT returned.
// returns a *RequestInformation when successful
func (m *WebhooksWithWebhook_ItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *WebhooksWithWebhook_ItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *WebhooksWithWebhook_ItemRequestBuilder when successful
func (m *WebhooksWithWebhook_ItemRequestBuilder) WithUrl(rawUrl string)(*WebhooksWithWebhook_ItemRequestBuilder) {
    return NewWebhooksWithWebhook_ItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
