// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AgentRequest struct {
    // The api_key property
    api_key *string
    // The callback_url property
    callback_url *string
    // The mode property
    mode *AgentRequest_mode
    // Optional stable profile identifier. When supplied on a successful sync `/v1/agent` call, the executed step trace is recorded into the in-process action cache (keyed by `(profile_id, task)`) and can be replayed via `POST /v1/agent/action-cache/replay`. Response payload includes `action_cache_recorded: true|false` so callers can confirm cache durability.
    profile_id *string
    // The proxy property
    proxy ProxyConfigable
    // Agent task payload; URL fields are policy-validated when present.
    task AgentRequest_taskable
    // The tenant_id property
    tenant_id *string
    // The workspace_id property
    workspace_id *string
}
// NewAgentRequest instantiates a new AgentRequest and sets the default values.
func NewAgentRequest()(*AgentRequest) {
    m := &AgentRequest{
    }
    modeValue := SYNC_AGENTREQUEST_MODE
    m.SetMode(&modeValue)
    return m
}
// CreateAgentRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAgentRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAgentRequest(), nil
}
// GetApiKey gets the api_key property value. The api_key property
// returns a *string when successful
func (m *AgentRequest) GetApiKey()(*string) {
    return m.api_key
}
// GetCallbackUrl gets the callback_url property value. The callback_url property
// returns a *string when successful
func (m *AgentRequest) GetCallbackUrl()(*string) {
    return m.callback_url
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *AgentRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["api_key"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetApiKey(val)
        }
        return nil
    }
    res["callback_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCallbackUrl(val)
        }
        return nil
    }
    res["mode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAgentRequest_mode)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMode(val.(*AgentRequest_mode))
        }
        return nil
    }
    res["profile_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfileId(val)
        }
        return nil
    }
    res["proxy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateProxyConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProxy(val.(ProxyConfigable))
        }
        return nil
    }
    res["task"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAgentRequest_taskFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTask(val.(AgentRequest_taskable))
        }
        return nil
    }
    res["tenant_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTenantId(val)
        }
        return nil
    }
    res["workspace_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWorkspaceId(val)
        }
        return nil
    }
    return res
}
// GetMode gets the mode property value. The mode property
// returns a *AgentRequest_mode when successful
func (m *AgentRequest) GetMode()(*AgentRequest_mode) {
    return m.mode
}
// GetProfileId gets the profile_id property value. Optional stable profile identifier. When supplied on a successful sync `/v1/agent` call, the executed step trace is recorded into the in-process action cache (keyed by `(profile_id, task)`) and can be replayed via `POST /v1/agent/action-cache/replay`. Response payload includes `action_cache_recorded: true|false` so callers can confirm cache durability.
// returns a *string when successful
func (m *AgentRequest) GetProfileId()(*string) {
    return m.profile_id
}
// GetProxy gets the proxy property value. The proxy property
// returns a ProxyConfigable when successful
func (m *AgentRequest) GetProxy()(ProxyConfigable) {
    return m.proxy
}
// GetTask gets the task property value. Agent task payload; URL fields are policy-validated when present.
// returns a AgentRequest_taskable when successful
func (m *AgentRequest) GetTask()(AgentRequest_taskable) {
    return m.task
}
// GetTenantId gets the tenant_id property value. The tenant_id property
// returns a *string when successful
func (m *AgentRequest) GetTenantId()(*string) {
    return m.tenant_id
}
// GetWorkspaceId gets the workspace_id property value. The workspace_id property
// returns a *string when successful
func (m *AgentRequest) GetWorkspaceId()(*string) {
    return m.workspace_id
}
// Serialize serializes information the current object
func (m *AgentRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("api_key", m.GetApiKey())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("callback_url", m.GetCallbackUrl())
        if err != nil {
            return err
        }
    }
    if m.GetMode() != nil {
        cast := (*m.GetMode()).String()
        err := writer.WriteStringValue("mode", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("profile_id", m.GetProfileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("proxy", m.GetProxy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("task", m.GetTask())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tenant_id", m.GetTenantId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("workspace_id", m.GetWorkspaceId())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetApiKey sets the api_key property value. The api_key property
func (m *AgentRequest) SetApiKey(value *string)() {
    m.api_key = value
}
// SetCallbackUrl sets the callback_url property value. The callback_url property
func (m *AgentRequest) SetCallbackUrl(value *string)() {
    m.callback_url = value
}
// SetMode sets the mode property value. The mode property
func (m *AgentRequest) SetMode(value *AgentRequest_mode)() {
    m.mode = value
}
// SetProfileId sets the profile_id property value. Optional stable profile identifier. When supplied on a successful sync `/v1/agent` call, the executed step trace is recorded into the in-process action cache (keyed by `(profile_id, task)`) and can be replayed via `POST /v1/agent/action-cache/replay`. Response payload includes `action_cache_recorded: true|false` so callers can confirm cache durability.
func (m *AgentRequest) SetProfileId(value *string)() {
    m.profile_id = value
}
// SetProxy sets the proxy property value. The proxy property
func (m *AgentRequest) SetProxy(value ProxyConfigable)() {
    m.proxy = value
}
// SetTask sets the task property value. Agent task payload; URL fields are policy-validated when present.
func (m *AgentRequest) SetTask(value AgentRequest_taskable)() {
    m.task = value
}
// SetTenantId sets the tenant_id property value. The tenant_id property
func (m *AgentRequest) SetTenantId(value *string)() {
    m.tenant_id = value
}
// SetWorkspaceId sets the workspace_id property value. The workspace_id property
func (m *AgentRequest) SetWorkspaceId(value *string)() {
    m.workspace_id = value
}
type AgentRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetApiKey()(*string)
    GetCallbackUrl()(*string)
    GetMode()(*AgentRequest_mode)
    GetProfileId()(*string)
    GetProxy()(ProxyConfigable)
    GetTask()(AgentRequest_taskable)
    GetTenantId()(*string)
    GetWorkspaceId()(*string)
    SetApiKey(value *string)()
    SetCallbackUrl(value *string)()
    SetMode(value *AgentRequest_mode)()
    SetProfileId(value *string)()
    SetProxy(value ProxyConfigable)()
    SetTask(value AgentRequest_taskable)()
    SetTenantId(value *string)()
    SetWorkspaceId(value *string)()
}
