// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type AgentRequest_task_steps_type int

const (
    ACT_AGENTREQUEST_TASK_STEPS_TYPE AgentRequest_task_steps_type = iota
    OBSERVE_AGENTREQUEST_TASK_STEPS_TYPE
    EXTRACT_AGENTREQUEST_TASK_STEPS_TYPE
)

func (i AgentRequest_task_steps_type) String() string {
    return []string{"act", "observe", "extract"}[i]
}
func ParseAgentRequest_task_steps_type(v string) (any, error) {
    result := ACT_AGENTREQUEST_TASK_STEPS_TYPE
    switch v {
        case "act":
            result = ACT_AGENTREQUEST_TASK_STEPS_TYPE
        case "observe":
            result = OBSERVE_AGENTREQUEST_TASK_STEPS_TYPE
        case "extract":
            result = EXTRACT_AGENTREQUEST_TASK_STEPS_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAgentRequest_task_steps_type(values []AgentRequest_task_steps_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AgentRequest_task_steps_type) isMultiValue() bool {
    return false
}
