// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AuditEventsResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The events property
    events []AuditEventOutable
    // The next_cursor property
    next_cursor AuditEventsResponse_AuditEventsResponse_next_cursorable
}
// AuditEventsResponse_AuditEventsResponse_next_cursor composed type wrapper for classes AuditEventsResponse_next_cursorMember1able, string
type AuditEventsResponse_AuditEventsResponse_next_cursor struct {
    // Composed type representation for type AuditEventsResponse_next_cursorMember1able
    auditEventsResponse_next_cursorMember1 AuditEventsResponse_next_cursorMember1able
    // Composed type representation for type string
    string *string
}
// NewAuditEventsResponse_AuditEventsResponse_next_cursor instantiates a new AuditEventsResponse_AuditEventsResponse_next_cursor and sets the default values.
func NewAuditEventsResponse_AuditEventsResponse_next_cursor()(*AuditEventsResponse_AuditEventsResponse_next_cursor) {
    m := &AuditEventsResponse_AuditEventsResponse_next_cursor{
    }
    return m
}
// CreateAuditEventsResponse_AuditEventsResponse_next_cursorFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuditEventsResponse_AuditEventsResponse_next_cursorFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewAuditEventsResponse_AuditEventsResponse_next_cursor()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateAuditEventsResponse_next_cursorMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(AuditEventsResponse_next_cursorMember1able); ok {
                result.SetAuditEventsResponseNextCursorMember1(cast)
            }
        }
    }
    return result, nil
}
// GetAuditEventsResponseNextCursorMember1 gets the AuditEventsResponse_next_cursorMember1 property value. Composed type representation for type AuditEventsResponse_next_cursorMember1able
// returns a AuditEventsResponse_next_cursorMember1able when successful
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) GetAuditEventsResponseNextCursorMember1()(AuditEventsResponse_next_cursorMember1able) {
    return m.auditEventsResponse_next_cursorMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetAuditEventsResponseNextCursorMember1() != nil {
        err := writer.WriteObjectValue("", m.GetAuditEventsResponseNextCursorMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAuditEventsResponseNextCursorMember1 sets the AuditEventsResponse_next_cursorMember1 property value. Composed type representation for type AuditEventsResponse_next_cursorMember1able
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) SetAuditEventsResponseNextCursorMember1(value AuditEventsResponse_next_cursorMember1able)() {
    m.auditEventsResponse_next_cursorMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *AuditEventsResponse_AuditEventsResponse_next_cursor) SetString(value *string)() {
    m.string = value
}
type AuditEventsResponse_AuditEventsResponse_next_cursorable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuditEventsResponseNextCursorMember1()(AuditEventsResponse_next_cursorMember1able)
    GetString()(*string)
    SetAuditEventsResponseNextCursorMember1(value AuditEventsResponse_next_cursorMember1able)()
    SetString(value *string)()
}
// NewAuditEventsResponse instantiates a new AuditEventsResponse and sets the default values.
func NewAuditEventsResponse()(*AuditEventsResponse) {
    m := &AuditEventsResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAuditEventsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuditEventsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuditEventsResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AuditEventsResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEvents gets the events property value. The events property
// returns a []AuditEventOutable when successful
func (m *AuditEventsResponse) GetEvents()([]AuditEventOutable) {
    return m.events
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *AuditEventsResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["events"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAuditEventOutFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AuditEventOutable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AuditEventOutable)
                }
            }
            m.SetEvents(res)
        }
        return nil
    }
    res["next_cursor"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAuditEventsResponse_AuditEventsResponse_next_cursorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNextCursor(val.(AuditEventsResponse_AuditEventsResponse_next_cursorable))
        }
        return nil
    }
    return res
}
// GetNextCursor gets the next_cursor property value. The next_cursor property
// returns a AuditEventsResponse_AuditEventsResponse_next_cursorable when successful
func (m *AuditEventsResponse) GetNextCursor()(AuditEventsResponse_AuditEventsResponse_next_cursorable) {
    return m.next_cursor
}
// Serialize serializes information the current object
func (m *AuditEventsResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetEvents() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetEvents()))
        for i, v := range m.GetEvents() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("events", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("next_cursor", m.GetNextCursor())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AuditEventsResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEvents sets the events property value. The events property
func (m *AuditEventsResponse) SetEvents(value []AuditEventOutable)() {
    m.events = value
}
// SetNextCursor sets the next_cursor property value. The next_cursor property
func (m *AuditEventsResponse) SetNextCursor(value AuditEventsResponse_AuditEventsResponse_next_cursorable)() {
    m.next_cursor = value
}
type AuditEventsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEvents()([]AuditEventOutable)
    GetNextCursor()(AuditEventsResponse_AuditEventsResponse_next_cursorable)
    SetEvents(value []AuditEventOutable)()
    SetNextCursor(value AuditEventsResponse_AuditEventsResponse_next_cursorable)()
}
