// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CookieDict struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The domain property
    domain CookieDict_CookieDict_domainable
    // The expires property
    expires CookieDict_CookieDict_expiresable
    // The httpOnly property
    httpOnly CookieDict_CookieDict_httpOnlyable
    // The name property
    name *string
    // The path property
    path CookieDict_CookieDict_pathable
    // The sameSite property
    sameSite CookieDict_CookieDict_sameSiteable
    // The secure property
    secure CookieDict_CookieDict_secureable
    // The url property
    url CookieDict_CookieDict_urlable
    // The value property
    value *string
}
// CookieDict_CookieDict_domain composed type wrapper for classes CookieDict_domainMember1able, string
type CookieDict_CookieDict_domain struct {
    // Composed type representation for type CookieDict_domainMember1able
    cookieDict_domainMember1 CookieDict_domainMember1able
    // Composed type representation for type string
    string *string
}
// NewCookieDict_CookieDict_domain instantiates a new CookieDict_CookieDict_domain and sets the default values.
func NewCookieDict_CookieDict_domain()(*CookieDict_CookieDict_domain) {
    m := &CookieDict_CookieDict_domain{
    }
    return m
}
// CreateCookieDict_CookieDict_domainFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_domainFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_domain()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_domainMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_domainMember1able); ok {
                result.SetCookieDictDomainMember1(cast)
            }
        }
    }
    return result, nil
}
// GetCookieDictDomainMember1 gets the CookieDict_domainMember1 property value. Composed type representation for type CookieDict_domainMember1able
// returns a CookieDict_domainMember1able when successful
func (m *CookieDict_CookieDict_domain) GetCookieDictDomainMember1()(CookieDict_domainMember1able) {
    return m.cookieDict_domainMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_domain) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_domain) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *CookieDict_CookieDict_domain) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_domain) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictDomainMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictDomainMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCookieDictDomainMember1 sets the CookieDict_domainMember1 property value. Composed type representation for type CookieDict_domainMember1able
func (m *CookieDict_CookieDict_domain) SetCookieDictDomainMember1(value CookieDict_domainMember1able)() {
    m.cookieDict_domainMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *CookieDict_CookieDict_domain) SetString(value *string)() {
    m.string = value
}
// CookieDict_CookieDict_expires composed type wrapper for classes CookieDict_expiresMember1able, float64
type CookieDict_CookieDict_expires struct {
    // Composed type representation for type CookieDict_expiresMember1able
    cookieDict_expiresMember1 CookieDict_expiresMember1able
    // Composed type representation for type float64
    double *float64
}
// NewCookieDict_CookieDict_expires instantiates a new CookieDict_CookieDict_expires and sets the default values.
func NewCookieDict_CookieDict_expires()(*CookieDict_CookieDict_expires) {
    m := &CookieDict_CookieDict_expires{
    }
    return m
}
// CreateCookieDict_CookieDict_expiresFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_expiresFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_expires()
    if parseNode != nil {
        if val, err := parseNode.GetFloat64Value(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetDouble(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_expiresMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_expiresMember1able); ok {
                result.SetCookieDictExpiresMember1(cast)
            }
        }
    }
    return result, nil
}
// GetCookieDictExpiresMember1 gets the CookieDict_expiresMember1 property value. Composed type representation for type CookieDict_expiresMember1able
// returns a CookieDict_expiresMember1able when successful
func (m *CookieDict_CookieDict_expires) GetCookieDictExpiresMember1()(CookieDict_expiresMember1able) {
    return m.cookieDict_expiresMember1
}
// GetDouble gets the double property value. Composed type representation for type float64
// returns a *float64 when successful
func (m *CookieDict_CookieDict_expires) GetDouble()(*float64) {
    return m.double
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_expires) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_expires) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_expires) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetDouble() != nil {
        err := writer.WriteFloat64Value("", m.GetDouble())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictExpiresMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictExpiresMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCookieDictExpiresMember1 sets the CookieDict_expiresMember1 property value. Composed type representation for type CookieDict_expiresMember1able
func (m *CookieDict_CookieDict_expires) SetCookieDictExpiresMember1(value CookieDict_expiresMember1able)() {
    m.cookieDict_expiresMember1 = value
}
// SetDouble sets the double property value. Composed type representation for type float64
func (m *CookieDict_CookieDict_expires) SetDouble(value *float64)() {
    m.double = value
}
// CookieDict_CookieDict_httpOnly composed type wrapper for classes bool, CookieDict_httpOnlyMember1able
type CookieDict_CookieDict_httpOnly struct {
    // Composed type representation for type bool
    boolean *bool
    // Composed type representation for type CookieDict_httpOnlyMember1able
    cookieDict_httpOnlyMember1 CookieDict_httpOnlyMember1able
}
// NewCookieDict_CookieDict_httpOnly instantiates a new CookieDict_CookieDict_httpOnly and sets the default values.
func NewCookieDict_CookieDict_httpOnly()(*CookieDict_CookieDict_httpOnly) {
    m := &CookieDict_CookieDict_httpOnly{
    }
    return m
}
// CreateCookieDict_CookieDict_httpOnlyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_httpOnlyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_httpOnly()
    if parseNode != nil {
        if val, err := parseNode.GetBoolValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetBoolean(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_httpOnlyMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_httpOnlyMember1able); ok {
                result.SetCookieDictHttpOnlyMember1(cast)
            }
        }
    }
    return result, nil
}
// GetBoolean gets the boolean property value. Composed type representation for type bool
// returns a *bool when successful
func (m *CookieDict_CookieDict_httpOnly) GetBoolean()(*bool) {
    return m.boolean
}
// GetCookieDictHttpOnlyMember1 gets the CookieDict_httpOnlyMember1 property value. Composed type representation for type CookieDict_httpOnlyMember1able
// returns a CookieDict_httpOnlyMember1able when successful
func (m *CookieDict_CookieDict_httpOnly) GetCookieDictHttpOnlyMember1()(CookieDict_httpOnlyMember1able) {
    return m.cookieDict_httpOnlyMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_httpOnly) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_httpOnly) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_httpOnly) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetBoolean() != nil {
        err := writer.WriteBoolValue("", m.GetBoolean())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictHttpOnlyMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictHttpOnlyMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetBoolean sets the boolean property value. Composed type representation for type bool
func (m *CookieDict_CookieDict_httpOnly) SetBoolean(value *bool)() {
    m.boolean = value
}
// SetCookieDictHttpOnlyMember1 sets the CookieDict_httpOnlyMember1 property value. Composed type representation for type CookieDict_httpOnlyMember1able
func (m *CookieDict_CookieDict_httpOnly) SetCookieDictHttpOnlyMember1(value CookieDict_httpOnlyMember1able)() {
    m.cookieDict_httpOnlyMember1 = value
}
// CookieDict_CookieDict_path composed type wrapper for classes CookieDict_pathMember1able, string
type CookieDict_CookieDict_path struct {
    // Composed type representation for type CookieDict_pathMember1able
    cookieDict_pathMember1 CookieDict_pathMember1able
    // Composed type representation for type string
    string *string
}
// NewCookieDict_CookieDict_path instantiates a new CookieDict_CookieDict_path and sets the default values.
func NewCookieDict_CookieDict_path()(*CookieDict_CookieDict_path) {
    m := &CookieDict_CookieDict_path{
    }
    return m
}
// CreateCookieDict_CookieDict_pathFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_pathFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_path()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_pathMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_pathMember1able); ok {
                result.SetCookieDictPathMember1(cast)
            }
        }
    }
    return result, nil
}
// GetCookieDictPathMember1 gets the CookieDict_pathMember1 property value. Composed type representation for type CookieDict_pathMember1able
// returns a CookieDict_pathMember1able when successful
func (m *CookieDict_CookieDict_path) GetCookieDictPathMember1()(CookieDict_pathMember1able) {
    return m.cookieDict_pathMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_path) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_path) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *CookieDict_CookieDict_path) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_path) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictPathMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictPathMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCookieDictPathMember1 sets the CookieDict_pathMember1 property value. Composed type representation for type CookieDict_pathMember1able
func (m *CookieDict_CookieDict_path) SetCookieDictPathMember1(value CookieDict_pathMember1able)() {
    m.cookieDict_pathMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *CookieDict_CookieDict_path) SetString(value *string)() {
    m.string = value
}
// CookieDict_CookieDict_sameSite composed type wrapper for classes CookieDict_sameSiteMember1able, string
type CookieDict_CookieDict_sameSite struct {
    // Composed type representation for type CookieDict_sameSiteMember1able
    cookieDict_sameSiteMember1 CookieDict_sameSiteMember1able
    // Composed type representation for type string
    string *string
}
// NewCookieDict_CookieDict_sameSite instantiates a new CookieDict_CookieDict_sameSite and sets the default values.
func NewCookieDict_CookieDict_sameSite()(*CookieDict_CookieDict_sameSite) {
    m := &CookieDict_CookieDict_sameSite{
    }
    return m
}
// CreateCookieDict_CookieDict_sameSiteFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_sameSiteFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_sameSite()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_sameSiteMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_sameSiteMember1able); ok {
                result.SetCookieDictSameSiteMember1(cast)
            }
        }
    }
    return result, nil
}
// GetCookieDictSameSiteMember1 gets the CookieDict_sameSiteMember1 property value. Composed type representation for type CookieDict_sameSiteMember1able
// returns a CookieDict_sameSiteMember1able when successful
func (m *CookieDict_CookieDict_sameSite) GetCookieDictSameSiteMember1()(CookieDict_sameSiteMember1able) {
    return m.cookieDict_sameSiteMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_sameSite) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_sameSite) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *CookieDict_CookieDict_sameSite) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_sameSite) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictSameSiteMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictSameSiteMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCookieDictSameSiteMember1 sets the CookieDict_sameSiteMember1 property value. Composed type representation for type CookieDict_sameSiteMember1able
func (m *CookieDict_CookieDict_sameSite) SetCookieDictSameSiteMember1(value CookieDict_sameSiteMember1able)() {
    m.cookieDict_sameSiteMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *CookieDict_CookieDict_sameSite) SetString(value *string)() {
    m.string = value
}
// CookieDict_CookieDict_secure composed type wrapper for classes bool, CookieDict_secureMember1able
type CookieDict_CookieDict_secure struct {
    // Composed type representation for type bool
    boolean *bool
    // Composed type representation for type CookieDict_secureMember1able
    cookieDict_secureMember1 CookieDict_secureMember1able
}
// NewCookieDict_CookieDict_secure instantiates a new CookieDict_CookieDict_secure and sets the default values.
func NewCookieDict_CookieDict_secure()(*CookieDict_CookieDict_secure) {
    m := &CookieDict_CookieDict_secure{
    }
    return m
}
// CreateCookieDict_CookieDict_secureFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_secureFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_secure()
    if parseNode != nil {
        if val, err := parseNode.GetBoolValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetBoolean(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_secureMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_secureMember1able); ok {
                result.SetCookieDictSecureMember1(cast)
            }
        }
    }
    return result, nil
}
// GetBoolean gets the boolean property value. Composed type representation for type bool
// returns a *bool when successful
func (m *CookieDict_CookieDict_secure) GetBoolean()(*bool) {
    return m.boolean
}
// GetCookieDictSecureMember1 gets the CookieDict_secureMember1 property value. Composed type representation for type CookieDict_secureMember1able
// returns a CookieDict_secureMember1able when successful
func (m *CookieDict_CookieDict_secure) GetCookieDictSecureMember1()(CookieDict_secureMember1able) {
    return m.cookieDict_secureMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_secure) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_secure) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_secure) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetBoolean() != nil {
        err := writer.WriteBoolValue("", m.GetBoolean())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictSecureMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictSecureMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetBoolean sets the boolean property value. Composed type representation for type bool
func (m *CookieDict_CookieDict_secure) SetBoolean(value *bool)() {
    m.boolean = value
}
// SetCookieDictSecureMember1 sets the CookieDict_secureMember1 property value. Composed type representation for type CookieDict_secureMember1able
func (m *CookieDict_CookieDict_secure) SetCookieDictSecureMember1(value CookieDict_secureMember1able)() {
    m.cookieDict_secureMember1 = value
}
// CookieDict_CookieDict_url composed type wrapper for classes CookieDict_urlMember1able, string
type CookieDict_CookieDict_url struct {
    // Composed type representation for type CookieDict_urlMember1able
    cookieDict_urlMember1 CookieDict_urlMember1able
    // Composed type representation for type string
    string *string
}
// NewCookieDict_CookieDict_url instantiates a new CookieDict_CookieDict_url and sets the default values.
func NewCookieDict_CookieDict_url()(*CookieDict_CookieDict_url) {
    m := &CookieDict_CookieDict_url{
    }
    return m
}
// CreateCookieDict_CookieDict_urlFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDict_CookieDict_urlFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCookieDict_CookieDict_url()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateCookieDict_urlMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(CookieDict_urlMember1able); ok {
                result.SetCookieDictUrlMember1(cast)
            }
        }
    }
    return result, nil
}
// GetCookieDictUrlMember1 gets the CookieDict_urlMember1 property value. Composed type representation for type CookieDict_urlMember1able
// returns a CookieDict_urlMember1able when successful
func (m *CookieDict_CookieDict_url) GetCookieDictUrlMember1()(CookieDict_urlMember1able) {
    return m.cookieDict_urlMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict_CookieDict_url) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CookieDict_CookieDict_url) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *CookieDict_CookieDict_url) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *CookieDict_CookieDict_url) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetCookieDictUrlMember1() != nil {
        err := writer.WriteObjectValue("", m.GetCookieDictUrlMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCookieDictUrlMember1 sets the CookieDict_urlMember1 property value. Composed type representation for type CookieDict_urlMember1able
func (m *CookieDict_CookieDict_url) SetCookieDictUrlMember1(value CookieDict_urlMember1able)() {
    m.cookieDict_urlMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *CookieDict_CookieDict_url) SetString(value *string)() {
    m.string = value
}
type CookieDict_CookieDict_domainable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCookieDictDomainMember1()(CookieDict_domainMember1able)
    GetString()(*string)
    SetCookieDictDomainMember1(value CookieDict_domainMember1able)()
    SetString(value *string)()
}
type CookieDict_CookieDict_expiresable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCookieDictExpiresMember1()(CookieDict_expiresMember1able)
    GetDouble()(*float64)
    SetCookieDictExpiresMember1(value CookieDict_expiresMember1able)()
    SetDouble(value *float64)()
}
type CookieDict_CookieDict_httpOnlyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBoolean()(*bool)
    GetCookieDictHttpOnlyMember1()(CookieDict_httpOnlyMember1able)
    SetBoolean(value *bool)()
    SetCookieDictHttpOnlyMember1(value CookieDict_httpOnlyMember1able)()
}
type CookieDict_CookieDict_pathable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCookieDictPathMember1()(CookieDict_pathMember1able)
    GetString()(*string)
    SetCookieDictPathMember1(value CookieDict_pathMember1able)()
    SetString(value *string)()
}
type CookieDict_CookieDict_sameSiteable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCookieDictSameSiteMember1()(CookieDict_sameSiteMember1able)
    GetString()(*string)
    SetCookieDictSameSiteMember1(value CookieDict_sameSiteMember1able)()
    SetString(value *string)()
}
type CookieDict_CookieDict_secureable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBoolean()(*bool)
    GetCookieDictSecureMember1()(CookieDict_secureMember1able)
    SetBoolean(value *bool)()
    SetCookieDictSecureMember1(value CookieDict_secureMember1able)()
}
type CookieDict_CookieDict_urlable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCookieDictUrlMember1()(CookieDict_urlMember1able)
    GetString()(*string)
    SetCookieDictUrlMember1(value CookieDict_urlMember1able)()
    SetString(value *string)()
}
// NewCookieDict instantiates a new CookieDict and sets the default values.
func NewCookieDict()(*CookieDict) {
    m := &CookieDict{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCookieDictFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCookieDictFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCookieDict(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CookieDict) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDomain gets the domain property value. The domain property
// returns a CookieDict_CookieDict_domainable when successful
func (m *CookieDict) GetDomain()(CookieDict_CookieDict_domainable) {
    return m.domain
}
// GetExpires gets the expires property value. The expires property
// returns a CookieDict_CookieDict_expiresable when successful
func (m *CookieDict) GetExpires()(CookieDict_CookieDict_expiresable) {
    return m.expires
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *CookieDict) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_domainFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDomain(val.(CookieDict_CookieDict_domainable))
        }
        return nil
    }
    res["expires"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_expiresFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpires(val.(CookieDict_CookieDict_expiresable))
        }
        return nil
    }
    res["httpOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_httpOnlyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHttpOnly(val.(CookieDict_CookieDict_httpOnlyable))
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["path"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_pathFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPath(val.(CookieDict_CookieDict_pathable))
        }
        return nil
    }
    res["sameSite"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_sameSiteFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSameSite(val.(CookieDict_CookieDict_sameSiteable))
        }
        return nil
    }
    res["secure"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_secureFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSecure(val.(CookieDict_CookieDict_secureable))
        }
        return nil
    }
    res["url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCookieDict_CookieDict_urlFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUrl(val.(CookieDict_CookieDict_urlable))
        }
        return nil
    }
    res["value"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetValue(val)
        }
        return nil
    }
    return res
}
// GetHttpOnly gets the httpOnly property value. The httpOnly property
// returns a CookieDict_CookieDict_httpOnlyable when successful
func (m *CookieDict) GetHttpOnly()(CookieDict_CookieDict_httpOnlyable) {
    return m.httpOnly
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *CookieDict) GetName()(*string) {
    return m.name
}
// GetPath gets the path property value. The path property
// returns a CookieDict_CookieDict_pathable when successful
func (m *CookieDict) GetPath()(CookieDict_CookieDict_pathable) {
    return m.path
}
// GetSameSite gets the sameSite property value. The sameSite property
// returns a CookieDict_CookieDict_sameSiteable when successful
func (m *CookieDict) GetSameSite()(CookieDict_CookieDict_sameSiteable) {
    return m.sameSite
}
// GetSecure gets the secure property value. The secure property
// returns a CookieDict_CookieDict_secureable when successful
func (m *CookieDict) GetSecure()(CookieDict_CookieDict_secureable) {
    return m.secure
}
// GetUrl gets the url property value. The url property
// returns a CookieDict_CookieDict_urlable when successful
func (m *CookieDict) GetUrl()(CookieDict_CookieDict_urlable) {
    return m.url
}
// GetValue gets the value property value. The value property
// returns a *string when successful
func (m *CookieDict) GetValue()(*string) {
    return m.value
}
// Serialize serializes information the current object
func (m *CookieDict) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("domain", m.GetDomain())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("expires", m.GetExpires())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("httpOnly", m.GetHttpOnly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("path", m.GetPath())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("sameSite", m.GetSameSite())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("secure", m.GetSecure())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("url", m.GetUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("value", m.GetValue())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CookieDict) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDomain sets the domain property value. The domain property
func (m *CookieDict) SetDomain(value CookieDict_CookieDict_domainable)() {
    m.domain = value
}
// SetExpires sets the expires property value. The expires property
func (m *CookieDict) SetExpires(value CookieDict_CookieDict_expiresable)() {
    m.expires = value
}
// SetHttpOnly sets the httpOnly property value. The httpOnly property
func (m *CookieDict) SetHttpOnly(value CookieDict_CookieDict_httpOnlyable)() {
    m.httpOnly = value
}
// SetName sets the name property value. The name property
func (m *CookieDict) SetName(value *string)() {
    m.name = value
}
// SetPath sets the path property value. The path property
func (m *CookieDict) SetPath(value CookieDict_CookieDict_pathable)() {
    m.path = value
}
// SetSameSite sets the sameSite property value. The sameSite property
func (m *CookieDict) SetSameSite(value CookieDict_CookieDict_sameSiteable)() {
    m.sameSite = value
}
// SetSecure sets the secure property value. The secure property
func (m *CookieDict) SetSecure(value CookieDict_CookieDict_secureable)() {
    m.secure = value
}
// SetUrl sets the url property value. The url property
func (m *CookieDict) SetUrl(value CookieDict_CookieDict_urlable)() {
    m.url = value
}
// SetValue sets the value property value. The value property
func (m *CookieDict) SetValue(value *string)() {
    m.value = value
}
type CookieDictable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDomain()(CookieDict_CookieDict_domainable)
    GetExpires()(CookieDict_CookieDict_expiresable)
    GetHttpOnly()(CookieDict_CookieDict_httpOnlyable)
    GetName()(*string)
    GetPath()(CookieDict_CookieDict_pathable)
    GetSameSite()(CookieDict_CookieDict_sameSiteable)
    GetSecure()(CookieDict_CookieDict_secureable)
    GetUrl()(CookieDict_CookieDict_urlable)
    GetValue()(*string)
    SetDomain(value CookieDict_CookieDict_domainable)()
    SetExpires(value CookieDict_CookieDict_expiresable)()
    SetHttpOnly(value CookieDict_CookieDict_httpOnlyable)()
    SetName(value *string)()
    SetPath(value CookieDict_CookieDict_pathable)()
    SetSameSite(value CookieDict_CookieDict_sameSiteable)()
    SetSecure(value CookieDict_CookieDict_secureable)()
    SetUrl(value CookieDict_CookieDict_urlable)()
    SetValue(value *string)()
}
