// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// IdentityPayload encrypted identity payload returned to the caller.
type IdentityPayload struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The alg property
    alg *string
    // The ciphertext property
    ciphertext *string
    // The iv property
    iv *string
    // The key_id property
    key_id *string
}
// NewIdentityPayload instantiates a new IdentityPayload and sets the default values.
func NewIdentityPayload()(*IdentityPayload) {
    m := &IdentityPayload{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateIdentityPayloadFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityPayloadFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIdentityPayload(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *IdentityPayload) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAlg gets the alg property value. The alg property
// returns a *string when successful
func (m *IdentityPayload) GetAlg()(*string) {
    return m.alg
}
// GetCiphertext gets the ciphertext property value. The ciphertext property
// returns a *string when successful
func (m *IdentityPayload) GetCiphertext()(*string) {
    return m.ciphertext
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityPayload) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["alg"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAlg(val)
        }
        return nil
    }
    res["ciphertext"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCiphertext(val)
        }
        return nil
    }
    res["iv"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIv(val)
        }
        return nil
    }
    res["key_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetKeyId(val)
        }
        return nil
    }
    return res
}
// GetIv gets the iv property value. The iv property
// returns a *string when successful
func (m *IdentityPayload) GetIv()(*string) {
    return m.iv
}
// GetKeyId gets the key_id property value. The key_id property
// returns a *string when successful
func (m *IdentityPayload) GetKeyId()(*string) {
    return m.key_id
}
// Serialize serializes information the current object
func (m *IdentityPayload) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("alg", m.GetAlg())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ciphertext", m.GetCiphertext())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("iv", m.GetIv())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("key_id", m.GetKeyId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *IdentityPayload) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAlg sets the alg property value. The alg property
func (m *IdentityPayload) SetAlg(value *string)() {
    m.alg = value
}
// SetCiphertext sets the ciphertext property value. The ciphertext property
func (m *IdentityPayload) SetCiphertext(value *string)() {
    m.ciphertext = value
}
// SetIv sets the iv property value. The iv property
func (m *IdentityPayload) SetIv(value *string)() {
    m.iv = value
}
// SetKeyId sets the key_id property value. The key_id property
func (m *IdentityPayload) SetKeyId(value *string)() {
    m.key_id = value
}
type IdentityPayloadable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAlg()(*string)
    GetCiphertext()(*string)
    GetIv()(*string)
    GetKeyId()(*string)
    SetAlg(value *string)()
    SetCiphertext(value *string)()
    SetIv(value *string)()
    SetKeyId(value *string)()
}
