// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// IdentityRequest request body for POST /v1/identity. extension (single-endpoint-with-source): source="user" → BYO local path; carries the full local identity payload. source="gc_identity" → managed cloud identity (paid plan). source=None → Legacy path (operating system and browser required). For legacy path with mobile operating system values (ios, android): device_model is required. For legacy path with desktop operating system values (macos, windows, linux): viewport is required.
type IdentityRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The browser property
    claim_browser IdentityRequest_IdentityRequest_claim_browserable
    // The operating system property
    claim_os IdentityRequest_IdentityRequest_claim_osable
    // The device_model property
    device_model IdentityRequest_IdentityRequest_device_modelable
    // The filter property
    filter i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The locale property
    locale IdentityRequest_IdentityRequest_localeable
    // The payload property
    payload i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The persist property
    persist *bool
    // The proxy property
    proxy IdentityRequest_IdentityRequest_proxyable
    // The source property
    source IdentityRequest_IdentityRequest_sourceable
    // The timezone property
    timezone IdentityRequest_IdentityRequest_timezoneable
    // The viewport property
    viewport IdentityRequest_IdentityRequest_viewportable
}
// IdentityRequest_IdentityRequest_claim_browser composed type wrapper for classes IdentityRequest_claim_browserMember1able, string
type IdentityRequest_IdentityRequest_claim_browser struct {
    // Composed type representation for type IdentityRequest_claim_browserMember1able
    identityRequest_claim_browserMember1 IdentityRequest_claim_browserMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_claim_browser instantiates a new IdentityRequest_IdentityRequest_claim_browser and sets the default values.
func NewIdentityRequest_IdentityRequest_claim_browser()(*IdentityRequest_IdentityRequest_claim_browser) {
    m := &IdentityRequest_IdentityRequest_claim_browser{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_claim_browserFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_claim_browserFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_claim_browser()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_claim_browserMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_claim_browserMember1able); ok {
                result.SetIdentityRequestClaimBrowserMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_claim_browser) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestClaimBrowserMember1 gets the IdentityRequest_claim_browserMember1 property value. Composed type representation for type IdentityRequest_claim_browserMember1able
// returns a IdentityRequest_claim_browserMember1able when successful
func (m *IdentityRequest_IdentityRequest_claim_browser) GetIdentityRequestClaimBrowserMember1()(IdentityRequest_claim_browserMember1able) {
    return m.identityRequest_claim_browserMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_claim_browser) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_claim_browser) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_claim_browser) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestClaimBrowserMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestClaimBrowserMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestClaimBrowserMember1 sets the IdentityRequest_claim_browserMember1 property value. Composed type representation for type IdentityRequest_claim_browserMember1able
func (m *IdentityRequest_IdentityRequest_claim_browser) SetIdentityRequestClaimBrowserMember1(value IdentityRequest_claim_browserMember1able)() {
    m.identityRequest_claim_browserMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_claim_browser) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_claim_os composed type wrapper for classes IdentityRequest_claim_osMember1able, string
type IdentityRequest_IdentityRequest_claim_os struct {
    // Composed type representation for type IdentityRequest_claim_osMember1able
    identityRequest_claim_osMember1 IdentityRequest_claim_osMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_claim_os instantiates a new IdentityRequest_IdentityRequest_claim_os and sets the default values.
func NewIdentityRequest_IdentityRequest_claim_os()(*IdentityRequest_IdentityRequest_claim_os) {
    m := &IdentityRequest_IdentityRequest_claim_os{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_claim_osFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_claim_osFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_claim_os()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_claim_osMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_claim_osMember1able); ok {
                result.SetIdentityRequestClaimOsMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_claim_os) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestClaimOsMember1 gets the IdentityRequest_claim_osMember1 property value. Composed type representation for type IdentityRequest_claim_osMember1able
// returns a IdentityRequest_claim_osMember1able when successful
func (m *IdentityRequest_IdentityRequest_claim_os) GetIdentityRequestClaimOsMember1()(IdentityRequest_claim_osMember1able) {
    return m.identityRequest_claim_osMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_claim_os) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_claim_os) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_claim_os) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestClaimOsMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestClaimOsMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestClaimOsMember1 sets the IdentityRequest_claim_osMember1 property value. Composed type representation for type IdentityRequest_claim_osMember1able
func (m *IdentityRequest_IdentityRequest_claim_os) SetIdentityRequestClaimOsMember1(value IdentityRequest_claim_osMember1able)() {
    m.identityRequest_claim_osMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_claim_os) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_device_model composed type wrapper for classes IdentityRequest_device_modelMember1able, string
type IdentityRequest_IdentityRequest_device_model struct {
    // Composed type representation for type IdentityRequest_device_modelMember1able
    identityRequest_device_modelMember1 IdentityRequest_device_modelMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_device_model instantiates a new IdentityRequest_IdentityRequest_device_model and sets the default values.
func NewIdentityRequest_IdentityRequest_device_model()(*IdentityRequest_IdentityRequest_device_model) {
    m := &IdentityRequest_IdentityRequest_device_model{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_device_modelFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_device_modelFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_device_model()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_device_modelMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_device_modelMember1able); ok {
                result.SetIdentityRequestDeviceModelMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_device_model) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestDeviceModelMember1 gets the IdentityRequest_device_modelMember1 property value. Composed type representation for type IdentityRequest_device_modelMember1able
// returns a IdentityRequest_device_modelMember1able when successful
func (m *IdentityRequest_IdentityRequest_device_model) GetIdentityRequestDeviceModelMember1()(IdentityRequest_device_modelMember1able) {
    return m.identityRequest_device_modelMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_device_model) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_device_model) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_device_model) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestDeviceModelMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestDeviceModelMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestDeviceModelMember1 sets the IdentityRequest_device_modelMember1 property value. Composed type representation for type IdentityRequest_device_modelMember1able
func (m *IdentityRequest_IdentityRequest_device_model) SetIdentityRequestDeviceModelMember1(value IdentityRequest_device_modelMember1able)() {
    m.identityRequest_device_modelMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_device_model) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_locale composed type wrapper for classes IdentityRequest_localeMember1able, string
type IdentityRequest_IdentityRequest_locale struct {
    // Composed type representation for type IdentityRequest_localeMember1able
    identityRequest_localeMember1 IdentityRequest_localeMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_locale instantiates a new IdentityRequest_IdentityRequest_locale and sets the default values.
func NewIdentityRequest_IdentityRequest_locale()(*IdentityRequest_IdentityRequest_locale) {
    m := &IdentityRequest_IdentityRequest_locale{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_localeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_localeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_locale()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_localeMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_localeMember1able); ok {
                result.SetIdentityRequestLocaleMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_locale) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestLocaleMember1 gets the IdentityRequest_localeMember1 property value. Composed type representation for type IdentityRequest_localeMember1able
// returns a IdentityRequest_localeMember1able when successful
func (m *IdentityRequest_IdentityRequest_locale) GetIdentityRequestLocaleMember1()(IdentityRequest_localeMember1able) {
    return m.identityRequest_localeMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_locale) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_locale) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_locale) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestLocaleMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestLocaleMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestLocaleMember1 sets the IdentityRequest_localeMember1 property value. Composed type representation for type IdentityRequest_localeMember1able
func (m *IdentityRequest_IdentityRequest_locale) SetIdentityRequestLocaleMember1(value IdentityRequest_localeMember1able)() {
    m.identityRequest_localeMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_locale) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_proxy composed type wrapper for classes IdentityRequest_proxyMember1able, string
type IdentityRequest_IdentityRequest_proxy struct {
    // Composed type representation for type IdentityRequest_proxyMember1able
    identityRequest_proxyMember1 IdentityRequest_proxyMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_proxy instantiates a new IdentityRequest_IdentityRequest_proxy and sets the default values.
func NewIdentityRequest_IdentityRequest_proxy()(*IdentityRequest_IdentityRequest_proxy) {
    m := &IdentityRequest_IdentityRequest_proxy{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_proxyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_proxyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_proxy()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_proxyMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_proxyMember1able); ok {
                result.SetIdentityRequestProxyMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_proxy) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestProxyMember1 gets the IdentityRequest_proxyMember1 property value. Composed type representation for type IdentityRequest_proxyMember1able
// returns a IdentityRequest_proxyMember1able when successful
func (m *IdentityRequest_IdentityRequest_proxy) GetIdentityRequestProxyMember1()(IdentityRequest_proxyMember1able) {
    return m.identityRequest_proxyMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_proxy) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_proxy) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_proxy) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestProxyMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestProxyMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestProxyMember1 sets the IdentityRequest_proxyMember1 property value. Composed type representation for type IdentityRequest_proxyMember1able
func (m *IdentityRequest_IdentityRequest_proxy) SetIdentityRequestProxyMember1(value IdentityRequest_proxyMember1able)() {
    m.identityRequest_proxyMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_proxy) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_source composed type wrapper for classes IdentityRequest_sourceMember1able, string
type IdentityRequest_IdentityRequest_source struct {
    // Composed type representation for type IdentityRequest_sourceMember1able
    identityRequest_sourceMember1 IdentityRequest_sourceMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_source instantiates a new IdentityRequest_IdentityRequest_source and sets the default values.
func NewIdentityRequest_IdentityRequest_source()(*IdentityRequest_IdentityRequest_source) {
    m := &IdentityRequest_IdentityRequest_source{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_sourceFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_sourceFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_source()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_sourceMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_sourceMember1able); ok {
                result.SetIdentityRequestSourceMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_source) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestSourceMember1 gets the IdentityRequest_sourceMember1 property value. Composed type representation for type IdentityRequest_sourceMember1able
// returns a IdentityRequest_sourceMember1able when successful
func (m *IdentityRequest_IdentityRequest_source) GetIdentityRequestSourceMember1()(IdentityRequest_sourceMember1able) {
    return m.identityRequest_sourceMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_source) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_source) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_source) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestSourceMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestSourceMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestSourceMember1 sets the IdentityRequest_sourceMember1 property value. Composed type representation for type IdentityRequest_sourceMember1able
func (m *IdentityRequest_IdentityRequest_source) SetIdentityRequestSourceMember1(value IdentityRequest_sourceMember1able)() {
    m.identityRequest_sourceMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_source) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_timezone composed type wrapper for classes IdentityRequest_timezoneMember1able, string
type IdentityRequest_IdentityRequest_timezone struct {
    // Composed type representation for type IdentityRequest_timezoneMember1able
    identityRequest_timezoneMember1 IdentityRequest_timezoneMember1able
    // Composed type representation for type string
    string *string
}
// NewIdentityRequest_IdentityRequest_timezone instantiates a new IdentityRequest_IdentityRequest_timezone and sets the default values.
func NewIdentityRequest_IdentityRequest_timezone()(*IdentityRequest_IdentityRequest_timezone) {
    m := &IdentityRequest_IdentityRequest_timezone{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_timezoneFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_timezoneFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_timezone()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_timezoneMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_timezoneMember1able); ok {
                result.SetIdentityRequestTimezoneMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_timezone) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestTimezoneMember1 gets the IdentityRequest_timezoneMember1 property value. Composed type representation for type IdentityRequest_timezoneMember1able
// returns a IdentityRequest_timezoneMember1able when successful
func (m *IdentityRequest_IdentityRequest_timezone) GetIdentityRequestTimezoneMember1()(IdentityRequest_timezoneMember1able) {
    return m.identityRequest_timezoneMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_timezone) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_timezone) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_timezone) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestTimezoneMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestTimezoneMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestTimezoneMember1 sets the IdentityRequest_timezoneMember1 property value. Composed type representation for type IdentityRequest_timezoneMember1able
func (m *IdentityRequest_IdentityRequest_timezone) SetIdentityRequestTimezoneMember1(value IdentityRequest_timezoneMember1able)() {
    m.identityRequest_timezoneMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_timezone) SetString(value *string)() {
    m.string = value
}
// IdentityRequest_IdentityRequest_viewport composed type wrapper for classes IdentityRequest_viewportMember1able, string, ViewportExactable
type IdentityRequest_IdentityRequest_viewport struct {
    // Composed type representation for type IdentityRequest_viewportMember1able
    identityRequest_viewportMember1 IdentityRequest_viewportMember1able
    // Composed type representation for type string
    string *string
    // Composed type representation for type ViewportExactable
    viewportExact ViewportExactable
}
// NewIdentityRequest_IdentityRequest_viewport instantiates a new IdentityRequest_IdentityRequest_viewport and sets the default values.
func NewIdentityRequest_IdentityRequest_viewport()(*IdentityRequest_IdentityRequest_viewport) {
    m := &IdentityRequest_IdentityRequest_viewport{
    }
    return m
}
// CreateIdentityRequest_IdentityRequest_viewportFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequest_IdentityRequest_viewportFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewIdentityRequest_IdentityRequest_viewport()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateIdentityRequest_viewportMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(IdentityRequest_viewportMember1able); ok {
                result.SetIdentityRequestViewportMember1(cast)
            }
        } else if val, err := parseNode.GetObjectValue(CreateViewportExactFromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(ViewportExactable); ok {
                result.SetViewportExact(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest_IdentityRequest_viewport) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIdentityRequestViewportMember1 gets the IdentityRequest_viewportMember1 property value. Composed type representation for type IdentityRequest_viewportMember1able
// returns a IdentityRequest_viewportMember1able when successful
func (m *IdentityRequest_IdentityRequest_viewport) GetIdentityRequestViewportMember1()(IdentityRequest_viewportMember1able) {
    return m.identityRequest_viewportMember1
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *IdentityRequest_IdentityRequest_viewport) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *IdentityRequest_IdentityRequest_viewport) GetString()(*string) {
    return m.string
}
// GetViewportExact gets the ViewportExact property value. Composed type representation for type ViewportExactable
// returns a ViewportExactable when successful
func (m *IdentityRequest_IdentityRequest_viewport) GetViewportExact()(ViewportExactable) {
    return m.viewportExact
}
// Serialize serializes information the current object
func (m *IdentityRequest_IdentityRequest_viewport) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetIdentityRequestViewportMember1() != nil {
        err := writer.WriteObjectValue("", m.GetIdentityRequestViewportMember1())
        if err != nil {
            return err
        }
    } else if m.GetViewportExact() != nil {
        err := writer.WriteObjectValue("", m.GetViewportExact())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetIdentityRequestViewportMember1 sets the IdentityRequest_viewportMember1 property value. Composed type representation for type IdentityRequest_viewportMember1able
func (m *IdentityRequest_IdentityRequest_viewport) SetIdentityRequestViewportMember1(value IdentityRequest_viewportMember1able)() {
    m.identityRequest_viewportMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *IdentityRequest_IdentityRequest_viewport) SetString(value *string)() {
    m.string = value
}
// SetViewportExact sets the ViewportExact property value. Composed type representation for type ViewportExactable
func (m *IdentityRequest_IdentityRequest_viewport) SetViewportExact(value ViewportExactable)() {
    m.viewportExact = value
}
type IdentityRequest_IdentityRequest_claim_browserable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestClaimBrowserMember1()(IdentityRequest_claim_browserMember1able)
    GetString()(*string)
    SetIdentityRequestClaimBrowserMember1(value IdentityRequest_claim_browserMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_claim_osable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestClaimOsMember1()(IdentityRequest_claim_osMember1able)
    GetString()(*string)
    SetIdentityRequestClaimOsMember1(value IdentityRequest_claim_osMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_device_modelable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestDeviceModelMember1()(IdentityRequest_device_modelMember1able)
    GetString()(*string)
    SetIdentityRequestDeviceModelMember1(value IdentityRequest_device_modelMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_localeable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestLocaleMember1()(IdentityRequest_localeMember1able)
    GetString()(*string)
    SetIdentityRequestLocaleMember1(value IdentityRequest_localeMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_proxyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestProxyMember1()(IdentityRequest_proxyMember1able)
    GetString()(*string)
    SetIdentityRequestProxyMember1(value IdentityRequest_proxyMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_sourceable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestSourceMember1()(IdentityRequest_sourceMember1able)
    GetString()(*string)
    SetIdentityRequestSourceMember1(value IdentityRequest_sourceMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_timezoneable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestTimezoneMember1()(IdentityRequest_timezoneMember1able)
    GetString()(*string)
    SetIdentityRequestTimezoneMember1(value IdentityRequest_timezoneMember1able)()
    SetString(value *string)()
}
type IdentityRequest_IdentityRequest_viewportable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentityRequestViewportMember1()(IdentityRequest_viewportMember1able)
    GetString()(*string)
    GetViewportExact()(ViewportExactable)
    SetIdentityRequestViewportMember1(value IdentityRequest_viewportMember1able)()
    SetString(value *string)()
    SetViewportExact(value ViewportExactable)()
}
// NewIdentityRequest instantiates a new IdentityRequest and sets the default values.
func NewIdentityRequest()(*IdentityRequest) {
    m := &IdentityRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    persistValue := false
    m.SetPersist(&persistValue)
    return m
}
// CreateIdentityRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIdentityRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIdentityRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *IdentityRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetClaimBrowser gets the browser property value. The browser property
// returns a IdentityRequest_IdentityRequest_claim_browserable when successful
func (m *IdentityRequest) GetClaimBrowser()(IdentityRequest_IdentityRequest_claim_browserable) {
    return m.claim_browser
}
// GetClaimOs gets the operating system property value. The operating system property
// returns a IdentityRequest_IdentityRequest_claim_osable when successful
func (m *IdentityRequest) GetClaimOs()(IdentityRequest_IdentityRequest_claim_osable) {
    return m.claim_os
}
// GetDeviceModel gets the device_model property value. The device_model property
// returns a IdentityRequest_IdentityRequest_device_modelable when successful
func (m *IdentityRequest) GetDeviceModel()(IdentityRequest_IdentityRequest_device_modelable) {
    return m.device_model
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *IdentityRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["claim_browser"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_claim_browserFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClaimBrowser(val.(IdentityRequest_IdentityRequest_claim_browserable))
        }
        return nil
    }
    res["claim_os"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_claim_osFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClaimOs(val.(IdentityRequest_IdentityRequest_claim_osable))
        }
        return nil
    }
    res["device_model"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_device_modelFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDeviceModel(val.(IdentityRequest_IdentityRequest_device_modelable))
        }
        return nil
    }
    res["filter"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFilter(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["locale"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_localeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocale(val.(IdentityRequest_IdentityRequest_localeable))
        }
        return nil
    }
    res["payload"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPayload(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["persist"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPersist(val)
        }
        return nil
    }
    res["proxy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_proxyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProxy(val.(IdentityRequest_IdentityRequest_proxyable))
        }
        return nil
    }
    res["source"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_sourceFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSource(val.(IdentityRequest_IdentityRequest_sourceable))
        }
        return nil
    }
    res["timezone"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_timezoneFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTimezone(val.(IdentityRequest_IdentityRequest_timezoneable))
        }
        return nil
    }
    res["viewport"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIdentityRequest_IdentityRequest_viewportFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetViewport(val.(IdentityRequest_IdentityRequest_viewportable))
        }
        return nil
    }
    return res
}
// GetFilter gets the filter property value. The filter property
// returns a UntypedNodeable when successful
func (m *IdentityRequest) GetFilter()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.filter
}
// GetLocale gets the locale property value. The locale property
// returns a IdentityRequest_IdentityRequest_localeable when successful
func (m *IdentityRequest) GetLocale()(IdentityRequest_IdentityRequest_localeable) {
    return m.locale
}
// GetPayload gets the payload property value. The payload property
// returns a UntypedNodeable when successful
func (m *IdentityRequest) GetPayload()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.payload
}
// GetPersist gets the persist property value. The persist property
// returns a *bool when successful
func (m *IdentityRequest) GetPersist()(*bool) {
    return m.persist
}
// GetProxy gets the proxy property value. The proxy property
// returns a IdentityRequest_IdentityRequest_proxyable when successful
func (m *IdentityRequest) GetProxy()(IdentityRequest_IdentityRequest_proxyable) {
    return m.proxy
}
// GetSource gets the source property value. The source property
// returns a IdentityRequest_IdentityRequest_sourceable when successful
func (m *IdentityRequest) GetSource()(IdentityRequest_IdentityRequest_sourceable) {
    return m.source
}
// GetTimezone gets the timezone property value. The timezone property
// returns a IdentityRequest_IdentityRequest_timezoneable when successful
func (m *IdentityRequest) GetTimezone()(IdentityRequest_IdentityRequest_timezoneable) {
    return m.timezone
}
// GetViewport gets the viewport property value. The viewport property
// returns a IdentityRequest_IdentityRequest_viewportable when successful
func (m *IdentityRequest) GetViewport()(IdentityRequest_IdentityRequest_viewportable) {
    return m.viewport
}
// Serialize serializes information the current object
func (m *IdentityRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("claim_browser", m.GetClaimBrowser())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("claim_os", m.GetClaimOs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("device_model", m.GetDeviceModel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("filter", m.GetFilter())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("locale", m.GetLocale())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("payload", m.GetPayload())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("persist", m.GetPersist())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("proxy", m.GetProxy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("source", m.GetSource())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("timezone", m.GetTimezone())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("viewport", m.GetViewport())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *IdentityRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetClaimBrowser sets the browser property value. The browser property
func (m *IdentityRequest) SetClaimBrowser(value IdentityRequest_IdentityRequest_claim_browserable)() {
    m.claim_browser = value
}
// SetClaimOs sets the operating system property value. The operating system property
func (m *IdentityRequest) SetClaimOs(value IdentityRequest_IdentityRequest_claim_osable)() {
    m.claim_os = value
}
// SetDeviceModel sets the device_model property value. The device_model property
func (m *IdentityRequest) SetDeviceModel(value IdentityRequest_IdentityRequest_device_modelable)() {
    m.device_model = value
}
// SetFilter sets the filter property value. The filter property
func (m *IdentityRequest) SetFilter(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.filter = value
}
// SetLocale sets the locale property value. The locale property
func (m *IdentityRequest) SetLocale(value IdentityRequest_IdentityRequest_localeable)() {
    m.locale = value
}
// SetPayload sets the payload property value. The payload property
func (m *IdentityRequest) SetPayload(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.payload = value
}
// SetPersist sets the persist property value. The persist property
func (m *IdentityRequest) SetPersist(value *bool)() {
    m.persist = value
}
// SetProxy sets the proxy property value. The proxy property
func (m *IdentityRequest) SetProxy(value IdentityRequest_IdentityRequest_proxyable)() {
    m.proxy = value
}
// SetSource sets the source property value. The source property
func (m *IdentityRequest) SetSource(value IdentityRequest_IdentityRequest_sourceable)() {
    m.source = value
}
// SetTimezone sets the timezone property value. The timezone property
func (m *IdentityRequest) SetTimezone(value IdentityRequest_IdentityRequest_timezoneable)() {
    m.timezone = value
}
// SetViewport sets the viewport property value. The viewport property
func (m *IdentityRequest) SetViewport(value IdentityRequest_IdentityRequest_viewportable)() {
    m.viewport = value
}
type IdentityRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetClaimBrowser()(IdentityRequest_IdentityRequest_claim_browserable)
    GetClaimOs()(IdentityRequest_IdentityRequest_claim_osable)
    GetDeviceModel()(IdentityRequest_IdentityRequest_device_modelable)
    GetFilter()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetLocale()(IdentityRequest_IdentityRequest_localeable)
    GetPayload()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetPersist()(*bool)
    GetProxy()(IdentityRequest_IdentityRequest_proxyable)
    GetSource()(IdentityRequest_IdentityRequest_sourceable)
    GetTimezone()(IdentityRequest_IdentityRequest_timezoneable)
    GetViewport()(IdentityRequest_IdentityRequest_viewportable)
    SetClaimBrowser(value IdentityRequest_IdentityRequest_claim_browserable)()
    SetClaimOs(value IdentityRequest_IdentityRequest_claim_osable)()
    SetDeviceModel(value IdentityRequest_IdentityRequest_device_modelable)()
    SetFilter(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetLocale(value IdentityRequest_IdentityRequest_localeable)()
    SetPayload(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetPersist(value *bool)()
    SetProxy(value IdentityRequest_IdentityRequest_proxyable)()
    SetSource(value IdentityRequest_IdentityRequest_sourceable)()
    SetTimezone(value IdentityRequest_IdentityRequest_timezoneable)()
    SetViewport(value IdentityRequest_IdentityRequest_viewportable)()
}
