// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MeResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The created_at property
    created_at MeResponse_MeResponse_created_atable
    // The email property
    email *string
    // The email_verified property
    email_verified *bool
    // The primary_team property
    primary_team TeamResponseable
    // The user_id property
    user_id *string
}
// MeResponse_MeResponse_created_at composed type wrapper for classes MeResponse_created_atMember1able, string
type MeResponse_MeResponse_created_at struct {
    // Composed type representation for type MeResponse_created_atMember1able
    meResponse_created_atMember1 MeResponse_created_atMember1able
    // Composed type representation for type string
    string *string
}
// NewMeResponse_MeResponse_created_at instantiates a new MeResponse_MeResponse_created_at and sets the default values.
func NewMeResponse_MeResponse_created_at()(*MeResponse_MeResponse_created_at) {
    m := &MeResponse_MeResponse_created_at{
    }
    return m
}
// CreateMeResponse_MeResponse_created_atFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMeResponse_MeResponse_created_atFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewMeResponse_MeResponse_created_at()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateMeResponse_created_atMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(MeResponse_created_atMember1able); ok {
                result.SetMeResponseCreatedAtMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *MeResponse_MeResponse_created_at) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *MeResponse_MeResponse_created_at) GetIsComposedType()(bool) {
    return true
}
// GetMeResponseCreatedAtMember1 gets the MeResponse_created_atMember1 property value. Composed type representation for type MeResponse_created_atMember1able
// returns a MeResponse_created_atMember1able when successful
func (m *MeResponse_MeResponse_created_at) GetMeResponseCreatedAtMember1()(MeResponse_created_atMember1able) {
    return m.meResponse_created_atMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *MeResponse_MeResponse_created_at) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *MeResponse_MeResponse_created_at) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetMeResponseCreatedAtMember1() != nil {
        err := writer.WriteObjectValue("", m.GetMeResponseCreatedAtMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetMeResponseCreatedAtMember1 sets the MeResponse_created_atMember1 property value. Composed type representation for type MeResponse_created_atMember1able
func (m *MeResponse_MeResponse_created_at) SetMeResponseCreatedAtMember1(value MeResponse_created_atMember1able)() {
    m.meResponse_created_atMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *MeResponse_MeResponse_created_at) SetString(value *string)() {
    m.string = value
}
type MeResponse_MeResponse_created_atable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMeResponseCreatedAtMember1()(MeResponse_created_atMember1able)
    GetString()(*string)
    SetMeResponseCreatedAtMember1(value MeResponse_created_atMember1able)()
    SetString(value *string)()
}
// NewMeResponse instantiates a new MeResponse and sets the default values.
func NewMeResponse()(*MeResponse) {
    m := &MeResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMeResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MeResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created_at property value. The created_at property
// returns a MeResponse_MeResponse_created_atable when successful
func (m *MeResponse) GetCreatedAt()(MeResponse_MeResponse_created_atable) {
    return m.created_at
}
// GetEmail gets the email property value. The email property
// returns a *string when successful
func (m *MeResponse) GetEmail()(*string) {
    return m.email
}
// GetEmailVerified gets the email_verified property value. The email_verified property
// returns a *bool when successful
func (m *MeResponse) GetEmailVerified()(*bool) {
    return m.email_verified
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *MeResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateMeResponse_MeResponse_created_atFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val.(MeResponse_MeResponse_created_atable))
        }
        return nil
    }
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["email_verified"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmailVerified(val)
        }
        return nil
    }
    res["primary_team"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateTeamResponseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrimaryTeam(val.(TeamResponseable))
        }
        return nil
    }
    res["user_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetPrimaryTeam gets the primary_team property value. The primary_team property
// returns a TeamResponseable when successful
func (m *MeResponse) GetPrimaryTeam()(TeamResponseable) {
    return m.primary_team
}
// GetUserId gets the user_id property value. The user_id property
// returns a *string when successful
func (m *MeResponse) GetUserId()(*string) {
    return m.user_id
}
// Serialize serializes information the current object
func (m *MeResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("email_verified", m.GetEmailVerified())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("primary_team", m.GetPrimaryTeam())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("user_id", m.GetUserId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MeResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created_at property value. The created_at property
func (m *MeResponse) SetCreatedAt(value MeResponse_MeResponse_created_atable)() {
    m.created_at = value
}
// SetEmail sets the email property value. The email property
func (m *MeResponse) SetEmail(value *string)() {
    m.email = value
}
// SetEmailVerified sets the email_verified property value. The email_verified property
func (m *MeResponse) SetEmailVerified(value *bool)() {
    m.email_verified = value
}
// SetPrimaryTeam sets the primary_team property value. The primary_team property
func (m *MeResponse) SetPrimaryTeam(value TeamResponseable)() {
    m.primary_team = value
}
// SetUserId sets the user_id property value. The user_id property
func (m *MeResponse) SetUserId(value *string)() {
    m.user_id = value
}
type MeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(MeResponse_MeResponse_created_atable)
    GetEmail()(*string)
    GetEmailVerified()(*bool)
    GetPrimaryTeam()(TeamResponseable)
    GetUserId()(*string)
    SetCreatedAt(value MeResponse_MeResponse_created_atable)()
    SetEmail(value *string)()
    SetEmailVerified(value *bool)()
    SetPrimaryTeam(value TeamResponseable)()
    SetUserId(value *string)()
}
