// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PdfRequest pOST /v1/pdf request body, render a URL to PDF. Renders the target URL to a PDF document. Supported on Chrome identities; requests that resolve to a Firefox or WebKit identity return 400 pdf_engine_unsupported. Security: - The URL is validated against private/loopback/metadata targets. - All traffic egresses through your configured proxy. - Subject to your daily request quota.
type PdfRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Engine override. PDF is chrome-only; 'firefox' or 'webkit' returns 400 pdf_engine_unsupported immediately (before dispatch).
    engine *PdfRequest_engine
    // Re-use a persisted identity.
    identity PdfRequest_PdfRequest_identityable
    // Two-letter country code to pin the exit country.
    identity_country PdfRequest_PdfRequest_identity_countryable
    // Inline identity specification.
    identity_spec i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // Browser language tag override (e.g. 'en-US').
    language PdfRequest_PdfRequest_languageable
    // Named persistent profile.
    profile PdfRequest_PdfRequest_profileable
    // Override proxy URL for this request.
    proxy PdfRequest_PdfRequest_proxyable
    // URL to render as PDF.
    url *string
}
// PdfRequest_PdfRequest_identity composed type wrapper for classes PdfRequest_identityMember1able, string
type PdfRequest_PdfRequest_identity struct {
    // Composed type representation for type PdfRequest_identityMember1able
    pdfRequest_identityMember1 PdfRequest_identityMember1able
    // Composed type representation for type string
    string *string
}
// NewPdfRequest_PdfRequest_identity instantiates a new PdfRequest_PdfRequest_identity and sets the default values.
func NewPdfRequest_PdfRequest_identity()(*PdfRequest_PdfRequest_identity) {
    m := &PdfRequest_PdfRequest_identity{
    }
    return m
}
// CreatePdfRequest_PdfRequest_identityFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequest_PdfRequest_identityFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPdfRequest_PdfRequest_identity()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreatePdfRequest_identityMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PdfRequest_identityMember1able); ok {
                result.SetPdfRequestIdentityMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest_PdfRequest_identity) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PdfRequest_PdfRequest_identity) GetIsComposedType()(bool) {
    return true
}
// GetPdfRequestIdentityMember1 gets the PdfRequest_identityMember1 property value. Composed type representation for type PdfRequest_identityMember1able
// returns a PdfRequest_identityMember1able when successful
func (m *PdfRequest_PdfRequest_identity) GetPdfRequestIdentityMember1()(PdfRequest_identityMember1able) {
    return m.pdfRequest_identityMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *PdfRequest_PdfRequest_identity) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *PdfRequest_PdfRequest_identity) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetPdfRequestIdentityMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPdfRequestIdentityMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPdfRequestIdentityMember1 sets the PdfRequest_identityMember1 property value. Composed type representation for type PdfRequest_identityMember1able
func (m *PdfRequest_PdfRequest_identity) SetPdfRequestIdentityMember1(value PdfRequest_identityMember1able)() {
    m.pdfRequest_identityMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *PdfRequest_PdfRequest_identity) SetString(value *string)() {
    m.string = value
}
// PdfRequest_PdfRequest_identity_country composed type wrapper for classes PdfRequest_identity_countryMember1able, string
type PdfRequest_PdfRequest_identity_country struct {
    // Composed type representation for type PdfRequest_identity_countryMember1able
    pdfRequest_identity_countryMember1 PdfRequest_identity_countryMember1able
    // Composed type representation for type string
    string *string
}
// NewPdfRequest_PdfRequest_identity_country instantiates a new PdfRequest_PdfRequest_identity_country and sets the default values.
func NewPdfRequest_PdfRequest_identity_country()(*PdfRequest_PdfRequest_identity_country) {
    m := &PdfRequest_PdfRequest_identity_country{
    }
    return m
}
// CreatePdfRequest_PdfRequest_identity_countryFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequest_PdfRequest_identity_countryFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPdfRequest_PdfRequest_identity_country()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreatePdfRequest_identity_countryMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PdfRequest_identity_countryMember1able); ok {
                result.SetPdfRequestIdentityCountryMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest_PdfRequest_identity_country) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PdfRequest_PdfRequest_identity_country) GetIsComposedType()(bool) {
    return true
}
// GetPdfRequestIdentityCountryMember1 gets the PdfRequest_identity_countryMember1 property value. Composed type representation for type PdfRequest_identity_countryMember1able
// returns a PdfRequest_identity_countryMember1able when successful
func (m *PdfRequest_PdfRequest_identity_country) GetPdfRequestIdentityCountryMember1()(PdfRequest_identity_countryMember1able) {
    return m.pdfRequest_identity_countryMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *PdfRequest_PdfRequest_identity_country) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *PdfRequest_PdfRequest_identity_country) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetPdfRequestIdentityCountryMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPdfRequestIdentityCountryMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPdfRequestIdentityCountryMember1 sets the PdfRequest_identity_countryMember1 property value. Composed type representation for type PdfRequest_identity_countryMember1able
func (m *PdfRequest_PdfRequest_identity_country) SetPdfRequestIdentityCountryMember1(value PdfRequest_identity_countryMember1able)() {
    m.pdfRequest_identity_countryMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *PdfRequest_PdfRequest_identity_country) SetString(value *string)() {
    m.string = value
}
// PdfRequest_PdfRequest_language composed type wrapper for classes PdfRequest_languageMember1able, string
type PdfRequest_PdfRequest_language struct {
    // Composed type representation for type PdfRequest_languageMember1able
    pdfRequest_languageMember1 PdfRequest_languageMember1able
    // Composed type representation for type string
    string *string
}
// NewPdfRequest_PdfRequest_language instantiates a new PdfRequest_PdfRequest_language and sets the default values.
func NewPdfRequest_PdfRequest_language()(*PdfRequest_PdfRequest_language) {
    m := &PdfRequest_PdfRequest_language{
    }
    return m
}
// CreatePdfRequest_PdfRequest_languageFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequest_PdfRequest_languageFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPdfRequest_PdfRequest_language()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreatePdfRequest_languageMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PdfRequest_languageMember1able); ok {
                result.SetPdfRequestLanguageMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest_PdfRequest_language) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PdfRequest_PdfRequest_language) GetIsComposedType()(bool) {
    return true
}
// GetPdfRequestLanguageMember1 gets the PdfRequest_languageMember1 property value. Composed type representation for type PdfRequest_languageMember1able
// returns a PdfRequest_languageMember1able when successful
func (m *PdfRequest_PdfRequest_language) GetPdfRequestLanguageMember1()(PdfRequest_languageMember1able) {
    return m.pdfRequest_languageMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *PdfRequest_PdfRequest_language) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *PdfRequest_PdfRequest_language) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetPdfRequestLanguageMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPdfRequestLanguageMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPdfRequestLanguageMember1 sets the PdfRequest_languageMember1 property value. Composed type representation for type PdfRequest_languageMember1able
func (m *PdfRequest_PdfRequest_language) SetPdfRequestLanguageMember1(value PdfRequest_languageMember1able)() {
    m.pdfRequest_languageMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *PdfRequest_PdfRequest_language) SetString(value *string)() {
    m.string = value
}
// PdfRequest_PdfRequest_profile composed type wrapper for classes PdfRequest_profileMember1able, string
type PdfRequest_PdfRequest_profile struct {
    // Composed type representation for type PdfRequest_profileMember1able
    pdfRequest_profileMember1 PdfRequest_profileMember1able
    // Composed type representation for type string
    string *string
}
// NewPdfRequest_PdfRequest_profile instantiates a new PdfRequest_PdfRequest_profile and sets the default values.
func NewPdfRequest_PdfRequest_profile()(*PdfRequest_PdfRequest_profile) {
    m := &PdfRequest_PdfRequest_profile{
    }
    return m
}
// CreatePdfRequest_PdfRequest_profileFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequest_PdfRequest_profileFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPdfRequest_PdfRequest_profile()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreatePdfRequest_profileMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PdfRequest_profileMember1able); ok {
                result.SetPdfRequestProfileMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest_PdfRequest_profile) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PdfRequest_PdfRequest_profile) GetIsComposedType()(bool) {
    return true
}
// GetPdfRequestProfileMember1 gets the PdfRequest_profileMember1 property value. Composed type representation for type PdfRequest_profileMember1able
// returns a PdfRequest_profileMember1able when successful
func (m *PdfRequest_PdfRequest_profile) GetPdfRequestProfileMember1()(PdfRequest_profileMember1able) {
    return m.pdfRequest_profileMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *PdfRequest_PdfRequest_profile) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *PdfRequest_PdfRequest_profile) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetPdfRequestProfileMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPdfRequestProfileMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPdfRequestProfileMember1 sets the PdfRequest_profileMember1 property value. Composed type representation for type PdfRequest_profileMember1able
func (m *PdfRequest_PdfRequest_profile) SetPdfRequestProfileMember1(value PdfRequest_profileMember1able)() {
    m.pdfRequest_profileMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *PdfRequest_PdfRequest_profile) SetString(value *string)() {
    m.string = value
}
// PdfRequest_PdfRequest_proxy composed type wrapper for classes PdfRequest_proxyMember1able, string
type PdfRequest_PdfRequest_proxy struct {
    // Composed type representation for type PdfRequest_proxyMember1able
    pdfRequest_proxyMember1 PdfRequest_proxyMember1able
    // Composed type representation for type string
    string *string
}
// NewPdfRequest_PdfRequest_proxy instantiates a new PdfRequest_PdfRequest_proxy and sets the default values.
func NewPdfRequest_PdfRequest_proxy()(*PdfRequest_PdfRequest_proxy) {
    m := &PdfRequest_PdfRequest_proxy{
    }
    return m
}
// CreatePdfRequest_PdfRequest_proxyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequest_PdfRequest_proxyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewPdfRequest_PdfRequest_proxy()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreatePdfRequest_proxyMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(PdfRequest_proxyMember1able); ok {
                result.SetPdfRequestProxyMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest_PdfRequest_proxy) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *PdfRequest_PdfRequest_proxy) GetIsComposedType()(bool) {
    return true
}
// GetPdfRequestProxyMember1 gets the PdfRequest_proxyMember1 property value. Composed type representation for type PdfRequest_proxyMember1able
// returns a PdfRequest_proxyMember1able when successful
func (m *PdfRequest_PdfRequest_proxy) GetPdfRequestProxyMember1()(PdfRequest_proxyMember1able) {
    return m.pdfRequest_proxyMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *PdfRequest_PdfRequest_proxy) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *PdfRequest_PdfRequest_proxy) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetPdfRequestProxyMember1() != nil {
        err := writer.WriteObjectValue("", m.GetPdfRequestProxyMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPdfRequestProxyMember1 sets the PdfRequest_proxyMember1 property value. Composed type representation for type PdfRequest_proxyMember1able
func (m *PdfRequest_PdfRequest_proxy) SetPdfRequestProxyMember1(value PdfRequest_proxyMember1able)() {
    m.pdfRequest_proxyMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *PdfRequest_PdfRequest_proxy) SetString(value *string)() {
    m.string = value
}
type PdfRequest_PdfRequest_identity_countryable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPdfRequestIdentityCountryMember1()(PdfRequest_identity_countryMember1able)
    GetString()(*string)
    SetPdfRequestIdentityCountryMember1(value PdfRequest_identity_countryMember1able)()
    SetString(value *string)()
}
type PdfRequest_PdfRequest_identityable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPdfRequestIdentityMember1()(PdfRequest_identityMember1able)
    GetString()(*string)
    SetPdfRequestIdentityMember1(value PdfRequest_identityMember1able)()
    SetString(value *string)()
}
type PdfRequest_PdfRequest_languageable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPdfRequestLanguageMember1()(PdfRequest_languageMember1able)
    GetString()(*string)
    SetPdfRequestLanguageMember1(value PdfRequest_languageMember1able)()
    SetString(value *string)()
}
type PdfRequest_PdfRequest_profileable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPdfRequestProfileMember1()(PdfRequest_profileMember1able)
    GetString()(*string)
    SetPdfRequestProfileMember1(value PdfRequest_profileMember1able)()
    SetString(value *string)()
}
type PdfRequest_PdfRequest_proxyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPdfRequestProxyMember1()(PdfRequest_proxyMember1able)
    GetString()(*string)
    SetPdfRequestProxyMember1(value PdfRequest_proxyMember1able)()
    SetString(value *string)()
}
// NewPdfRequest instantiates a new PdfRequest and sets the default values.
func NewPdfRequest()(*PdfRequest) {
    m := &PdfRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    engineValue := AUTO_PDFREQUEST_ENGINE
    m.SetEngine(&engineValue)
    return m
}
// CreatePdfRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePdfRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPdfRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PdfRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEngine gets the engine property value. Engine override. PDF is chrome-only; 'firefox' or 'webkit' returns 400 pdf_engine_unsupported immediately (before dispatch).
// returns a *PdfRequest_engine when successful
func (m *PdfRequest) GetEngine()(*PdfRequest_engine) {
    return m.engine
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *PdfRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["engine"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePdfRequest_engine)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEngine(val.(*PdfRequest_engine))
        }
        return nil
    }
    res["identity"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePdfRequest_PdfRequest_identityFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentity(val.(PdfRequest_PdfRequest_identityable))
        }
        return nil
    }
    res["identity_country"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePdfRequest_PdfRequest_identity_countryFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentityCountry(val.(PdfRequest_PdfRequest_identity_countryable))
        }
        return nil
    }
    res["identity_spec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentitySpec(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["language"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePdfRequest_PdfRequest_languageFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLanguage(val.(PdfRequest_PdfRequest_languageable))
        }
        return nil
    }
    res["profile"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePdfRequest_PdfRequest_profileFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfile(val.(PdfRequest_PdfRequest_profileable))
        }
        return nil
    }
    res["proxy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePdfRequest_PdfRequest_proxyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProxy(val.(PdfRequest_PdfRequest_proxyable))
        }
        return nil
    }
    res["url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUrl(val)
        }
        return nil
    }
    return res
}
// GetIdentity gets the identity property value. Re-use a persisted identity.
// returns a PdfRequest_PdfRequest_identityable when successful
func (m *PdfRequest) GetIdentity()(PdfRequest_PdfRequest_identityable) {
    return m.identity
}
// GetIdentityCountry gets the identity_country property value. Two-letter country code to pin the exit country.
// returns a PdfRequest_PdfRequest_identity_countryable when successful
func (m *PdfRequest) GetIdentityCountry()(PdfRequest_PdfRequest_identity_countryable) {
    return m.identity_country
}
// GetIdentitySpec gets the identity_spec property value. Inline identity specification.
// returns a UntypedNodeable when successful
func (m *PdfRequest) GetIdentitySpec()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.identity_spec
}
// GetLanguage gets the language property value. Browser language tag override (e.g. 'en-US').
// returns a PdfRequest_PdfRequest_languageable when successful
func (m *PdfRequest) GetLanguage()(PdfRequest_PdfRequest_languageable) {
    return m.language
}
// GetProfile gets the profile property value. Named persistent profile.
// returns a PdfRequest_PdfRequest_profileable when successful
func (m *PdfRequest) GetProfile()(PdfRequest_PdfRequest_profileable) {
    return m.profile
}
// GetProxy gets the proxy property value. Override proxy URL for this request.
// returns a PdfRequest_PdfRequest_proxyable when successful
func (m *PdfRequest) GetProxy()(PdfRequest_PdfRequest_proxyable) {
    return m.proxy
}
// GetUrl gets the url property value. URL to render as PDF.
// returns a *string when successful
func (m *PdfRequest) GetUrl()(*string) {
    return m.url
}
// Serialize serializes information the current object
func (m *PdfRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetEngine() != nil {
        cast := (*m.GetEngine()).String()
        err := writer.WriteStringValue("engine", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("identity", m.GetIdentity())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("identity_country", m.GetIdentityCountry())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("identity_spec", m.GetIdentitySpec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("language", m.GetLanguage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("profile", m.GetProfile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("proxy", m.GetProxy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("url", m.GetUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PdfRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEngine sets the engine property value. Engine override. PDF is chrome-only; 'firefox' or 'webkit' returns 400 pdf_engine_unsupported immediately (before dispatch).
func (m *PdfRequest) SetEngine(value *PdfRequest_engine)() {
    m.engine = value
}
// SetIdentity sets the identity property value. Re-use a persisted identity.
func (m *PdfRequest) SetIdentity(value PdfRequest_PdfRequest_identityable)() {
    m.identity = value
}
// SetIdentityCountry sets the identity_country property value. Two-letter country code to pin the exit country.
func (m *PdfRequest) SetIdentityCountry(value PdfRequest_PdfRequest_identity_countryable)() {
    m.identity_country = value
}
// SetIdentitySpec sets the identity_spec property value. Inline identity specification.
func (m *PdfRequest) SetIdentitySpec(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.identity_spec = value
}
// SetLanguage sets the language property value. Browser language tag override (e.g. 'en-US').
func (m *PdfRequest) SetLanguage(value PdfRequest_PdfRequest_languageable)() {
    m.language = value
}
// SetProfile sets the profile property value. Named persistent profile.
func (m *PdfRequest) SetProfile(value PdfRequest_PdfRequest_profileable)() {
    m.profile = value
}
// SetProxy sets the proxy property value. Override proxy URL for this request.
func (m *PdfRequest) SetProxy(value PdfRequest_PdfRequest_proxyable)() {
    m.proxy = value
}
// SetUrl sets the url property value. URL to render as PDF.
func (m *PdfRequest) SetUrl(value *string)() {
    m.url = value
}
type PdfRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEngine()(*PdfRequest_engine)
    GetIdentity()(PdfRequest_PdfRequest_identityable)
    GetIdentityCountry()(PdfRequest_PdfRequest_identity_countryable)
    GetIdentitySpec()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetLanguage()(PdfRequest_PdfRequest_languageable)
    GetProfile()(PdfRequest_PdfRequest_profileable)
    GetProxy()(PdfRequest_PdfRequest_proxyable)
    GetUrl()(*string)
    SetEngine(value *PdfRequest_engine)()
    SetIdentity(value PdfRequest_PdfRequest_identityable)()
    SetIdentityCountry(value PdfRequest_PdfRequest_identity_countryable)()
    SetIdentitySpec(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetLanguage(value PdfRequest_PdfRequest_languageable)()
    SetProfile(value PdfRequest_PdfRequest_profileable)()
    SetProxy(value PdfRequest_PdfRequest_proxyable)()
    SetUrl(value *string)()
}
