// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ProfileCreateRequest pOST /v1/profiles body, create a named persistent profile.
type ProfileCreateRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Public IdentityRequest spec (operating system, browser, device, viewport, locale, and timezone). The profile mints a STABLE deterministic identity_id from it, so every scrape with profile=<name> rehydrates the SAME fingerprint. When omitted, a default desktop-chrome identity is minted.
    identity_spec i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // Profile name. Unique per org (409 on conflict).
    name *string
    // Optional storage_state id to bind (cookies/localStorage).
    storage_state_id ProfileCreateRequest_ProfileCreateRequest_storage_state_idable
}
// ProfileCreateRequest_ProfileCreateRequest_storage_state_id composed type wrapper for classes ProfileCreateRequest_storage_state_idMember1able, string
type ProfileCreateRequest_ProfileCreateRequest_storage_state_id struct {
    // Composed type representation for type ProfileCreateRequest_storage_state_idMember1able
    profileCreateRequest_storage_state_idMember1 ProfileCreateRequest_storage_state_idMember1able
    // Composed type representation for type string
    string *string
}
// NewProfileCreateRequest_ProfileCreateRequest_storage_state_id instantiates a new ProfileCreateRequest_ProfileCreateRequest_storage_state_id and sets the default values.
func NewProfileCreateRequest_ProfileCreateRequest_storage_state_id()(*ProfileCreateRequest_ProfileCreateRequest_storage_state_id) {
    m := &ProfileCreateRequest_ProfileCreateRequest_storage_state_id{
    }
    return m
}
// CreateProfileCreateRequest_ProfileCreateRequest_storage_state_idFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProfileCreateRequest_ProfileCreateRequest_storage_state_idFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewProfileCreateRequest_ProfileCreateRequest_storage_state_id()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateProfileCreateRequest_storage_state_idMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(ProfileCreateRequest_storage_state_idMember1able); ok {
                result.SetProfileCreateRequestStorageStateIdMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) GetIsComposedType()(bool) {
    return true
}
// GetProfileCreateRequestStorageStateIdMember1 gets the ProfileCreateRequest_storage_state_idMember1 property value. Composed type representation for type ProfileCreateRequest_storage_state_idMember1able
// returns a ProfileCreateRequest_storage_state_idMember1able when successful
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) GetProfileCreateRequestStorageStateIdMember1()(ProfileCreateRequest_storage_state_idMember1able) {
    return m.profileCreateRequest_storage_state_idMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetProfileCreateRequestStorageStateIdMember1() != nil {
        err := writer.WriteObjectValue("", m.GetProfileCreateRequestStorageStateIdMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetProfileCreateRequestStorageStateIdMember1 sets the ProfileCreateRequest_storage_state_idMember1 property value. Composed type representation for type ProfileCreateRequest_storage_state_idMember1able
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) SetProfileCreateRequestStorageStateIdMember1(value ProfileCreateRequest_storage_state_idMember1able)() {
    m.profileCreateRequest_storage_state_idMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *ProfileCreateRequest_ProfileCreateRequest_storage_state_id) SetString(value *string)() {
    m.string = value
}
type ProfileCreateRequest_ProfileCreateRequest_storage_state_idable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetProfileCreateRequestStorageStateIdMember1()(ProfileCreateRequest_storage_state_idMember1able)
    GetString()(*string)
    SetProfileCreateRequestStorageStateIdMember1(value ProfileCreateRequest_storage_state_idMember1able)()
    SetString(value *string)()
}
// NewProfileCreateRequest instantiates a new ProfileCreateRequest and sets the default values.
func NewProfileCreateRequest()(*ProfileCreateRequest) {
    m := &ProfileCreateRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateProfileCreateRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProfileCreateRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewProfileCreateRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ProfileCreateRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *ProfileCreateRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["identity_spec"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentitySpec(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["storage_state_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateProfileCreateRequest_ProfileCreateRequest_storage_state_idFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStorageStateId(val.(ProfileCreateRequest_ProfileCreateRequest_storage_state_idable))
        }
        return nil
    }
    return res
}
// GetIdentitySpec gets the identity_spec property value. Public IdentityRequest spec (operating system, browser, device, viewport, locale, and timezone). The profile mints a STABLE deterministic identity_id from it, so every scrape with profile=<name> rehydrates the SAME fingerprint. When omitted, a default desktop-chrome identity is minted.
// returns a UntypedNodeable when successful
func (m *ProfileCreateRequest) GetIdentitySpec()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.identity_spec
}
// GetName gets the name property value. Profile name. Unique per org (409 on conflict).
// returns a *string when successful
func (m *ProfileCreateRequest) GetName()(*string) {
    return m.name
}
// GetStorageStateId gets the storage_state_id property value. Optional storage_state id to bind (cookies/localStorage).
// returns a ProfileCreateRequest_ProfileCreateRequest_storage_state_idable when successful
func (m *ProfileCreateRequest) GetStorageStateId()(ProfileCreateRequest_ProfileCreateRequest_storage_state_idable) {
    return m.storage_state_id
}
// Serialize serializes information the current object
func (m *ProfileCreateRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("identity_spec", m.GetIdentitySpec())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("storage_state_id", m.GetStorageStateId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ProfileCreateRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetIdentitySpec sets the identity_spec property value. Public IdentityRequest spec (operating system, browser, device, viewport, locale, and timezone). The profile mints a STABLE deterministic identity_id from it, so every scrape with profile=<name> rehydrates the SAME fingerprint. When omitted, a default desktop-chrome identity is minted.
func (m *ProfileCreateRequest) SetIdentitySpec(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.identity_spec = value
}
// SetName sets the name property value. Profile name. Unique per org (409 on conflict).
func (m *ProfileCreateRequest) SetName(value *string)() {
    m.name = value
}
// SetStorageStateId sets the storage_state_id property value. Optional storage_state id to bind (cookies/localStorage).
func (m *ProfileCreateRequest) SetStorageStateId(value ProfileCreateRequest_ProfileCreateRequest_storage_state_idable)() {
    m.storage_state_id = value
}
type ProfileCreateRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetIdentitySpec()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetName()(*string)
    GetStorageStateId()(ProfileCreateRequest_ProfileCreateRequest_storage_state_idable)
    SetIdentitySpec(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetName(value *string)()
    SetStorageStateId(value ProfileCreateRequest_ProfileCreateRequest_storage_state_idable)()
}
