// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SessionCreateRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The engine property
    engine *SessionCreateRequest_engine
    // The identity_config property
    identity_config i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // Named persistent profile (gologin parity). Rehydrates the saved identity bundle for this session, same deterministic fingerprint as /v1/scrape with profile=<name>.
    profile SessionCreateRequest_SessionCreateRequest_profileable
    // The proxy property
    proxy i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
}
// SessionCreateRequest_SessionCreateRequest_profile composed type wrapper for classes SessionCreateRequest_profileMember1able, string
type SessionCreateRequest_SessionCreateRequest_profile struct {
    // Composed type representation for type SessionCreateRequest_profileMember1able
    sessionCreateRequest_profileMember1 SessionCreateRequest_profileMember1able
    // Composed type representation for type string
    string *string
}
// NewSessionCreateRequest_SessionCreateRequest_profile instantiates a new SessionCreateRequest_SessionCreateRequest_profile and sets the default values.
func NewSessionCreateRequest_SessionCreateRequest_profile()(*SessionCreateRequest_SessionCreateRequest_profile) {
    m := &SessionCreateRequest_SessionCreateRequest_profile{
    }
    return m
}
// CreateSessionCreateRequest_SessionCreateRequest_profileFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSessionCreateRequest_SessionCreateRequest_profileFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewSessionCreateRequest_SessionCreateRequest_profile()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateSessionCreateRequest_profileMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(SessionCreateRequest_profileMember1able); ok {
                result.SetSessionCreateRequestProfileMember1(cast)
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *SessionCreateRequest_SessionCreateRequest_profile) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *SessionCreateRequest_SessionCreateRequest_profile) GetIsComposedType()(bool) {
    return true
}
// GetSessionCreateRequestProfileMember1 gets the SessionCreateRequest_profileMember1 property value. Composed type representation for type SessionCreateRequest_profileMember1able
// returns a SessionCreateRequest_profileMember1able when successful
func (m *SessionCreateRequest_SessionCreateRequest_profile) GetSessionCreateRequestProfileMember1()(SessionCreateRequest_profileMember1able) {
    return m.sessionCreateRequest_profileMember1
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *SessionCreateRequest_SessionCreateRequest_profile) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *SessionCreateRequest_SessionCreateRequest_profile) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetSessionCreateRequestProfileMember1() != nil {
        err := writer.WriteObjectValue("", m.GetSessionCreateRequestProfileMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetSessionCreateRequestProfileMember1 sets the SessionCreateRequest_profileMember1 property value. Composed type representation for type SessionCreateRequest_profileMember1able
func (m *SessionCreateRequest_SessionCreateRequest_profile) SetSessionCreateRequestProfileMember1(value SessionCreateRequest_profileMember1able)() {
    m.sessionCreateRequest_profileMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *SessionCreateRequest_SessionCreateRequest_profile) SetString(value *string)() {
    m.string = value
}
type SessionCreateRequest_SessionCreateRequest_profileable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSessionCreateRequestProfileMember1()(SessionCreateRequest_profileMember1able)
    GetString()(*string)
    SetSessionCreateRequestProfileMember1(value SessionCreateRequest_profileMember1able)()
    SetString(value *string)()
}
// NewSessionCreateRequest instantiates a new SessionCreateRequest and sets the default values.
func NewSessionCreateRequest()(*SessionCreateRequest) {
    m := &SessionCreateRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    engineValue := CHROME_SESSIONCREATEREQUEST_ENGINE
    m.SetEngine(&engineValue)
    return m
}
// CreateSessionCreateRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSessionCreateRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSessionCreateRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SessionCreateRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEngine gets the engine property value. The engine property
// returns a *SessionCreateRequest_engine when successful
func (m *SessionCreateRequest) GetEngine()(*SessionCreateRequest_engine) {
    return m.engine
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *SessionCreateRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["engine"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseSessionCreateRequest_engine)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEngine(val.(*SessionCreateRequest_engine))
        }
        return nil
    }
    res["identity_config"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentityConfig(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["profile"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSessionCreateRequest_SessionCreateRequest_profileFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfile(val.(SessionCreateRequest_SessionCreateRequest_profileable))
        }
        return nil
    }
    res["proxy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProxy(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    return res
}
// GetIdentityConfig gets the identity_config property value. The identity_config property
// returns a UntypedNodeable when successful
func (m *SessionCreateRequest) GetIdentityConfig()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.identity_config
}
// GetProfile gets the profile property value. Named persistent profile (gologin parity). Rehydrates the saved identity bundle for this session, same deterministic fingerprint as /v1/scrape with profile=<name>.
// returns a SessionCreateRequest_SessionCreateRequest_profileable when successful
func (m *SessionCreateRequest) GetProfile()(SessionCreateRequest_SessionCreateRequest_profileable) {
    return m.profile
}
// GetProxy gets the proxy property value. The proxy property
// returns a UntypedNodeable when successful
func (m *SessionCreateRequest) GetProxy()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.proxy
}
// Serialize serializes information the current object
func (m *SessionCreateRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetEngine() != nil {
        cast := (*m.GetEngine()).String()
        err := writer.WriteStringValue("engine", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("identity_config", m.GetIdentityConfig())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("profile", m.GetProfile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("proxy", m.GetProxy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SessionCreateRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEngine sets the engine property value. The engine property
func (m *SessionCreateRequest) SetEngine(value *SessionCreateRequest_engine)() {
    m.engine = value
}
// SetIdentityConfig sets the identity_config property value. The identity_config property
func (m *SessionCreateRequest) SetIdentityConfig(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.identity_config = value
}
// SetProfile sets the profile property value. Named persistent profile (gologin parity). Rehydrates the saved identity bundle for this session, same deterministic fingerprint as /v1/scrape with profile=<name>.
func (m *SessionCreateRequest) SetProfile(value SessionCreateRequest_SessionCreateRequest_profileable)() {
    m.profile = value
}
// SetProxy sets the proxy property value. The proxy property
func (m *SessionCreateRequest) SetProxy(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.proxy = value
}
type SessionCreateRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEngine()(*SessionCreateRequest_engine)
    GetIdentityConfig()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetProfile()(SessionCreateRequest_SessionCreateRequest_profileable)
    GetProxy()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    SetEngine(value *SessionCreateRequest_engine)()
    SetIdentityConfig(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetProfile(value SessionCreateRequest_SessionCreateRequest_profileable)()
    SetProxy(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
}
