// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// StorageStateAttachRequest pOST /v1/storage-states/{id_or_name}/attach, sticky-attach to a profile.
type StorageStateAttachRequest struct {
    // Profile to attach this storage state to (sticky per).
    profile_id *string
}
// NewStorageStateAttachRequest instantiates a new StorageStateAttachRequest and sets the default values.
func NewStorageStateAttachRequest()(*StorageStateAttachRequest) {
    m := &StorageStateAttachRequest{
    }
    return m
}
// CreateStorageStateAttachRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStorageStateAttachRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStorageStateAttachRequest(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *StorageStateAttachRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["profile_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfileId(val)
        }
        return nil
    }
    return res
}
// GetProfileId gets the profile_id property value. Profile to attach this storage state to (sticky per).
// returns a *string when successful
func (m *StorageStateAttachRequest) GetProfileId()(*string) {
    return m.profile_id
}
// Serialize serializes information the current object
func (m *StorageStateAttachRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("profile_id", m.GetProfileId())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetProfileId sets the profile_id property value. Profile to attach this storage state to (sticky per).
func (m *StorageStateAttachRequest) SetProfileId(value *string)() {
    m.profile_id = value
}
type StorageStateAttachRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetProfileId()(*string)
    SetProfileId(value *string)()
}
