// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UploadBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The content_base64 property
    content_base64 *string
    // The filename property
    filename *string
    // The mime property
    mime *string
    // The profile_id property
    profile_id *string
    // The selector property
    selector *string
}
// NewUploadBody instantiates a new UploadBody and sets the default values.
func NewUploadBody()(*UploadBody) {
    m := &UploadBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUploadBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUploadBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUploadBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UploadBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetContentBase64 gets the content_base64 property value. The content_base64 property
// returns a *string when successful
func (m *UploadBody) GetContentBase64()(*string) {
    return m.content_base64
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *UploadBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["content_base64"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContentBase64(val)
        }
        return nil
    }
    res["filename"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFilename(val)
        }
        return nil
    }
    res["mime"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMime(val)
        }
        return nil
    }
    res["profile_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfileId(val)
        }
        return nil
    }
    res["selector"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSelector(val)
        }
        return nil
    }
    return res
}
// GetFilename gets the filename property value. The filename property
// returns a *string when successful
func (m *UploadBody) GetFilename()(*string) {
    return m.filename
}
// GetMime gets the mime property value. The mime property
// returns a *string when successful
func (m *UploadBody) GetMime()(*string) {
    return m.mime
}
// GetProfileId gets the profile_id property value. The profile_id property
// returns a *string when successful
func (m *UploadBody) GetProfileId()(*string) {
    return m.profile_id
}
// GetSelector gets the selector property value. The selector property
// returns a *string when successful
func (m *UploadBody) GetSelector()(*string) {
    return m.selector
}
// Serialize serializes information the current object
func (m *UploadBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("content_base64", m.GetContentBase64())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("filename", m.GetFilename())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("mime", m.GetMime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("profile_id", m.GetProfileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("selector", m.GetSelector())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UploadBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetContentBase64 sets the content_base64 property value. The content_base64 property
func (m *UploadBody) SetContentBase64(value *string)() {
    m.content_base64 = value
}
// SetFilename sets the filename property value. The filename property
func (m *UploadBody) SetFilename(value *string)() {
    m.filename = value
}
// SetMime sets the mime property value. The mime property
func (m *UploadBody) SetMime(value *string)() {
    m.mime = value
}
// SetProfileId sets the profile_id property value. The profile_id property
func (m *UploadBody) SetProfileId(value *string)() {
    m.profile_id = value
}
// SetSelector sets the selector property value. The selector property
func (m *UploadBody) SetSelector(value *string)() {
    m.selector = value
}
type UploadBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetContentBase64()(*string)
    GetFilename()(*string)
    GetMime()(*string)
    GetProfileId()(*string)
    GetSelector()(*string)
    SetContentBase64(value *string)()
    SetFilename(value *string)()
    SetMime(value *string)()
    SetProfileId(value *string)()
    SetSelector(value *string)()
}
