// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// WebhookCreateResponse response for POST /v1/webhooks (201 Created). `secret` is the plaintext signing secret returned ONCE. Store itimmediately, subsequent GET calls return WebhookPublic which excludes the secret.
type WebhookCreateResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Plaintext signing secret. Returned only once, store it now.
    secret *string
    // Public webhook subscription details. The signing secret is never included in list or get responses, it is returned only at creation time or after a secret rotation.
    webhook WebhookPublicable
}
// NewWebhookCreateResponse instantiates a new WebhookCreateResponse and sets the default values.
func NewWebhookCreateResponse()(*WebhookCreateResponse) {
    m := &WebhookCreateResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateWebhookCreateResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateWebhookCreateResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewWebhookCreateResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *WebhookCreateResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91. ParseNode)(error) when successful
func (m *WebhookCreateResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["secret"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSecret(val)
        }
        return nil
    }
    res["webhook"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateWebhookPublicFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWebhook(val.(WebhookPublicable))
        }
        return nil
    }
    return res
}
// GetSecret gets the secret property value. Plaintext signing secret. Returned only once, store it now.
// returns a *string when successful
func (m *WebhookCreateResponse) GetSecret()(*string) {
    return m.secret
}
// GetWebhook gets the webhook property value. Public webhook subscription details. The signing secret is never included in list or get responses, it is returned only at creation time or after a secret rotation.
// returns a WebhookPublicable when successful
func (m *WebhookCreateResponse) GetWebhook()(WebhookPublicable) {
    return m.webhook
}
// Serialize serializes information the current object
func (m *WebhookCreateResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("secret", m.GetSecret())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("webhook", m.GetWebhook())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *WebhookCreateResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSecret sets the secret property value. Plaintext signing secret. Returned only once, store it now.
func (m *WebhookCreateResponse) SetSecret(value *string)() {
    m.secret = value
}
// SetWebhook sets the webhook property value. Public webhook subscription details. The signing secret is never included in list or get responses, it is returned only at creation time or after a secret rotation.
func (m *WebhookCreateResponse) SetWebhook(value WebhookPublicable)() {
    m.webhook = value
}
type WebhookCreateResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSecret()(*string)
    GetWebhook()(WebhookPublicable)
    SetSecret(value *string)()
    SetWebhook(value WebhookPublicable)()
}
