// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DeepCrawlBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The filters property
    filters []FilterSpecable
    // The include_sitemaps property
    include_sitemaps *bool
    // The max_depth property
    max_depth *int32
    // The max_urls property
    max_urls *int32
    // The respect_robots property
    respect_robots *bool
    // Routing mode. auto (default) = we pick the cheapest network that succeeds and automatically escalate on a block. standard = normal targets only. premium = always use our premium network. Most callers should leave this at auto.
    routing_mode *DeepCrawlBody_routing_mode
    // The scorer property
    scorer ScorerSpecable
    // The seed_urls property
    seed_urls []string
    // The strategy property
    strategy *string
    // The stream property
    stream *bool
    // The timeout_s property
    timeout_s DeepCrawlBody_DeepCrawlBody_timeout_sable
    // The wait_until property
    wait_until DeepCrawlBody_DeepCrawlBody_wait_untilable
    // The webhook_url property
    webhook_url DeepCrawlBody_DeepCrawlBody_webhook_urlable
}
// DeepCrawlBody_DeepCrawlBody_timeout_s composed type wrapper for classes DeepCrawlBody_timeout_sMember1able, int32
type DeepCrawlBody_DeepCrawlBody_timeout_s struct {
    // Composed type representation for type DeepCrawlBody_timeout_sMember1able
    deepCrawlBody_timeout_sMember1 DeepCrawlBody_timeout_sMember1able
    // Composed type representation for type int32
    integer *int32
}
// NewDeepCrawlBody_DeepCrawlBody_timeout_s instantiates a new DeepCrawlBody_DeepCrawlBody_timeout_s and sets the default values.
func NewDeepCrawlBody_DeepCrawlBody_timeout_s()(*DeepCrawlBody_DeepCrawlBody_timeout_s) {
    m := &DeepCrawlBody_DeepCrawlBody_timeout_s{
    }
    return m
}
// CreateDeepCrawlBody_DeepCrawlBody_timeout_sFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeepCrawlBody_DeepCrawlBody_timeout_sFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewDeepCrawlBody_DeepCrawlBody_timeout_s()
    if parseNode != nil {
        if val, err := parseNode.GetInt32Value(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetInteger(val)
        } else if val, err := parseNode.GetObjectValue(CreateDeepCrawlBody_timeout_sMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(DeepCrawlBody_timeout_sMember1able); ok {
                result.SetDeepCrawlBodyTimeoutSMember1(cast)
            }
        }
    }
    return result, nil
}
// GetDeepCrawlBodyTimeoutSMember1 gets the DeepCrawlBody_timeout_sMember1 property value. Composed type representation for type DeepCrawlBody_timeout_sMember1able
// returns a DeepCrawlBody_timeout_sMember1able when successful
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) GetDeepCrawlBodyTimeoutSMember1()(DeepCrawlBody_timeout_sMember1able) {
    return m.deepCrawlBody_timeout_sMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetInteger gets the integer property value. Composed type representation for type int32
// returns a *int32 when successful
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) GetInteger()(*int32) {
    return m.integer
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetInteger() != nil {
        err := writer.WriteInt32Value("", m.GetInteger())
        if err != nil {
            return err
        }
    } else if m.GetDeepCrawlBodyTimeoutSMember1() != nil {
        err := writer.WriteObjectValue("", m.GetDeepCrawlBodyTimeoutSMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDeepCrawlBodyTimeoutSMember1 sets the DeepCrawlBody_timeout_sMember1 property value. Composed type representation for type DeepCrawlBody_timeout_sMember1able
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) SetDeepCrawlBodyTimeoutSMember1(value DeepCrawlBody_timeout_sMember1able)() {
    m.deepCrawlBody_timeout_sMember1 = value
}
// SetInteger sets the integer property value. Composed type representation for type int32
func (m *DeepCrawlBody_DeepCrawlBody_timeout_s) SetInteger(value *int32)() {
    m.integer = value
}
// DeepCrawlBody_DeepCrawlBody_wait_until composed type wrapper for classes DeepCrawlBody_wait_untilMember1able, string
type DeepCrawlBody_DeepCrawlBody_wait_until struct {
    // Composed type representation for type DeepCrawlBody_wait_untilMember1able
    deepCrawlBody_wait_untilMember1 DeepCrawlBody_wait_untilMember1able
    // Composed type representation for type string
    string *string
}
// NewDeepCrawlBody_DeepCrawlBody_wait_until instantiates a new DeepCrawlBody_DeepCrawlBody_wait_until and sets the default values.
func NewDeepCrawlBody_DeepCrawlBody_wait_until()(*DeepCrawlBody_DeepCrawlBody_wait_until) {
    m := &DeepCrawlBody_DeepCrawlBody_wait_until{
    }
    return m
}
// CreateDeepCrawlBody_DeepCrawlBody_wait_untilFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeepCrawlBody_DeepCrawlBody_wait_untilFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewDeepCrawlBody_DeepCrawlBody_wait_until()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateDeepCrawlBody_wait_untilMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(DeepCrawlBody_wait_untilMember1able); ok {
                result.SetDeepCrawlBodyWaitUntilMember1(cast)
            }
        }
    }
    return result, nil
}
// GetDeepCrawlBodyWaitUntilMember1 gets the DeepCrawlBody_wait_untilMember1 property value. Composed type representation for type DeepCrawlBody_wait_untilMember1able
// returns a DeepCrawlBody_wait_untilMember1able when successful
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) GetDeepCrawlBodyWaitUntilMember1()(DeepCrawlBody_wait_untilMember1able) {
    return m.deepCrawlBody_wait_untilMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetDeepCrawlBodyWaitUntilMember1() != nil {
        err := writer.WriteObjectValue("", m.GetDeepCrawlBodyWaitUntilMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDeepCrawlBodyWaitUntilMember1 sets the DeepCrawlBody_wait_untilMember1 property value. Composed type representation for type DeepCrawlBody_wait_untilMember1able
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) SetDeepCrawlBodyWaitUntilMember1(value DeepCrawlBody_wait_untilMember1able)() {
    m.deepCrawlBody_wait_untilMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *DeepCrawlBody_DeepCrawlBody_wait_until) SetString(value *string)() {
    m.string = value
}
// DeepCrawlBody_DeepCrawlBody_webhook_url composed type wrapper for classes DeepCrawlBody_webhook_urlMember1able, string
type DeepCrawlBody_DeepCrawlBody_webhook_url struct {
    // Composed type representation for type DeepCrawlBody_webhook_urlMember1able
    deepCrawlBody_webhook_urlMember1 DeepCrawlBody_webhook_urlMember1able
    // Composed type representation for type string
    string *string
}
// NewDeepCrawlBody_DeepCrawlBody_webhook_url instantiates a new DeepCrawlBody_DeepCrawlBody_webhook_url and sets the default values.
func NewDeepCrawlBody_DeepCrawlBody_webhook_url()(*DeepCrawlBody_DeepCrawlBody_webhook_url) {
    m := &DeepCrawlBody_DeepCrawlBody_webhook_url{
    }
    return m
}
// CreateDeepCrawlBody_DeepCrawlBody_webhook_urlFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeepCrawlBody_DeepCrawlBody_webhook_urlFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewDeepCrawlBody_DeepCrawlBody_webhook_url()
    if parseNode != nil {
        if val, err := parseNode.GetStringValue(); val != nil {
            if err != nil {
                return nil, err
            }
            result.SetString(val)
        } else if val, err := parseNode.GetObjectValue(CreateDeepCrawlBody_webhook_urlMember1FromDiscriminatorValue); val != nil {
            if err != nil {
                return nil, err
            }
            if cast, ok := val.(DeepCrawlBody_webhook_urlMember1able); ok {
                result.SetDeepCrawlBodyWebhookUrlMember1(cast)
            }
        }
    }
    return result, nil
}
// GetDeepCrawlBodyWebhookUrlMember1 gets the DeepCrawlBody_webhook_urlMember1 property value. Composed type representation for type DeepCrawlBody_webhook_urlMember1able
// returns a DeepCrawlBody_webhook_urlMember1able when successful
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) GetDeepCrawlBodyWebhookUrlMember1()(DeepCrawlBody_webhook_urlMember1able) {
    return m.deepCrawlBody_webhook_urlMember1
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) GetIsComposedType()(bool) {
    return true
}
// GetString gets the string property value. Composed type representation for type string
// returns a *string when successful
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) GetString()(*string) {
    return m.string
}
// Serialize serializes information the current object
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetString() != nil {
        err := writer.WriteStringValue("", m.GetString())
        if err != nil {
            return err
        }
    } else if m.GetDeepCrawlBodyWebhookUrlMember1() != nil {
        err := writer.WriteObjectValue("", m.GetDeepCrawlBodyWebhookUrlMember1())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDeepCrawlBodyWebhookUrlMember1 sets the DeepCrawlBody_webhook_urlMember1 property value. Composed type representation for type DeepCrawlBody_webhook_urlMember1able
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) SetDeepCrawlBodyWebhookUrlMember1(value DeepCrawlBody_webhook_urlMember1able)() {
    m.deepCrawlBody_webhook_urlMember1 = value
}
// SetString sets the string property value. Composed type representation for type string
func (m *DeepCrawlBody_DeepCrawlBody_webhook_url) SetString(value *string)() {
    m.string = value
}
type DeepCrawlBody_DeepCrawlBody_timeout_sable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDeepCrawlBodyTimeoutSMember1()(DeepCrawlBody_timeout_sMember1able)
    GetInteger()(*int32)
    SetDeepCrawlBodyTimeoutSMember1(value DeepCrawlBody_timeout_sMember1able)()
    SetInteger(value *int32)()
}
type DeepCrawlBody_DeepCrawlBody_wait_untilable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDeepCrawlBodyWaitUntilMember1()(DeepCrawlBody_wait_untilMember1able)
    GetString()(*string)
    SetDeepCrawlBodyWaitUntilMember1(value DeepCrawlBody_wait_untilMember1able)()
    SetString(value *string)()
}
type DeepCrawlBody_DeepCrawlBody_webhook_urlable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDeepCrawlBodyWebhookUrlMember1()(DeepCrawlBody_webhook_urlMember1able)
    GetString()(*string)
    SetDeepCrawlBodyWebhookUrlMember1(value DeepCrawlBody_webhook_urlMember1able)()
    SetString(value *string)()
}
// NewDeepCrawlBody instantiates a new DeepCrawlBody and sets the default values.
func NewDeepCrawlBody()(*DeepCrawlBody) {
    m := &DeepCrawlBody{
    }
    m.SetAdditionalData(make(map[string]any))
    include_sitemapsValue := false
    m.SetIncludeSitemaps(&include_sitemapsValue)
    max_depthValue := int32(3)
    m.SetMaxDepth(&max_depthValue)
    max_urlsValue := int32(1000)
    m.SetMaxUrls(&max_urlsValue)
    respect_robotsValue := true
    m.SetRespectRobots(&respect_robotsValue)
    routing_modeValue := AUTO_DEEPCRAWLBODY_ROUTING_MODE
    m.SetRoutingMode(&routing_modeValue)
    strategyValue := "bfs"
    m.SetStrategy(&strategyValue)
    streamValue := false
    m.SetStream(&streamValue)
    return m
}
// CreateDeepCrawlBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeepCrawlBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeepCrawlBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DeepCrawlBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeepCrawlBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["filters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateFilterSpecFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]FilterSpecable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(FilterSpecable)
                }
            }
            m.SetFilters(res)
        }
        return nil
    }
    res["include_sitemaps"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIncludeSitemaps(val)
        }
        return nil
    }
    res["max_depth"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMaxDepth(val)
        }
        return nil
    }
    res["max_urls"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMaxUrls(val)
        }
        return nil
    }
    res["respect_robots"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRespectRobots(val)
        }
        return nil
    }
    res["routing_mode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseDeepCrawlBody_routing_mode)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoutingMode(val.(*DeepCrawlBody_routing_mode))
        }
        return nil
    }
    res["scorer"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateScorerSpecFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScorer(val.(ScorerSpecable))
        }
        return nil
    }
    res["seed_urls"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetSeedUrls(res)
        }
        return nil
    }
    res["strategy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStrategy(val)
        }
        return nil
    }
    res["stream"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStream(val)
        }
        return nil
    }
    res["timeout_s"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDeepCrawlBody_DeepCrawlBody_timeout_sFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTimeoutS(val.(DeepCrawlBody_DeepCrawlBody_timeout_sable))
        }
        return nil
    }
    res["wait_until"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDeepCrawlBody_DeepCrawlBody_wait_untilFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWaitUntil(val.(DeepCrawlBody_DeepCrawlBody_wait_untilable))
        }
        return nil
    }
    res["webhook_url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDeepCrawlBody_DeepCrawlBody_webhook_urlFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWebhookUrl(val.(DeepCrawlBody_DeepCrawlBody_webhook_urlable))
        }
        return nil
    }
    return res
}
// GetFilters gets the filters property value. The filters property
// returns a []FilterSpecable when successful
func (m *DeepCrawlBody) GetFilters()([]FilterSpecable) {
    return m.filters
}
// GetIncludeSitemaps gets the include_sitemaps property value. The include_sitemaps property
// returns a *bool when successful
func (m *DeepCrawlBody) GetIncludeSitemaps()(*bool) {
    return m.include_sitemaps
}
// GetMaxDepth gets the max_depth property value. The max_depth property
// returns a *int32 when successful
func (m *DeepCrawlBody) GetMaxDepth()(*int32) {
    return m.max_depth
}
// GetMaxUrls gets the max_urls property value. The max_urls property
// returns a *int32 when successful
func (m *DeepCrawlBody) GetMaxUrls()(*int32) {
    return m.max_urls
}
// GetRespectRobots gets the respect_robots property value. The respect_robots property
// returns a *bool when successful
func (m *DeepCrawlBody) GetRespectRobots()(*bool) {
    return m.respect_robots
}
// GetRoutingMode gets the routing_mode property value. Routing mode. auto (default) = we pick the cheapest network that succeeds and automatically escalate on a block. standard = normal targets only. premium = always use our premium network. Most callers should leave this at auto.
// returns a *DeepCrawlBody_routing_mode when successful
func (m *DeepCrawlBody) GetRoutingMode()(*DeepCrawlBody_routing_mode) {
    return m.routing_mode
}
// GetScorer gets the scorer property value. The scorer property
// returns a ScorerSpecable when successful
func (m *DeepCrawlBody) GetScorer()(ScorerSpecable) {
    return m.scorer
}
// GetSeedUrls gets the seed_urls property value. The seed_urls property
// returns a []string when successful
func (m *DeepCrawlBody) GetSeedUrls()([]string) {
    return m.seed_urls
}
// GetStrategy gets the strategy property value. The strategy property
// returns a *string when successful
func (m *DeepCrawlBody) GetStrategy()(*string) {
    return m.strategy
}
// GetStream gets the stream property value. The stream property
// returns a *bool when successful
func (m *DeepCrawlBody) GetStream()(*bool) {
    return m.stream
}
// GetTimeoutS gets the timeout_s property value. The timeout_s property
// returns a DeepCrawlBody_DeepCrawlBody_timeout_sable when successful
func (m *DeepCrawlBody) GetTimeoutS()(DeepCrawlBody_DeepCrawlBody_timeout_sable) {
    return m.timeout_s
}
// GetWaitUntil gets the wait_until property value. The wait_until property
// returns a DeepCrawlBody_DeepCrawlBody_wait_untilable when successful
func (m *DeepCrawlBody) GetWaitUntil()(DeepCrawlBody_DeepCrawlBody_wait_untilable) {
    return m.wait_until
}
// GetWebhookUrl gets the webhook_url property value. The webhook_url property
// returns a DeepCrawlBody_DeepCrawlBody_webhook_urlable when successful
func (m *DeepCrawlBody) GetWebhookUrl()(DeepCrawlBody_DeepCrawlBody_webhook_urlable) {
    return m.webhook_url
}
// Serialize serializes information the current object
func (m *DeepCrawlBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetFilters() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetFilters()))
        for i, v := range m.GetFilters() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("filters", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("include_sitemaps", m.GetIncludeSitemaps())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("max_depth", m.GetMaxDepth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("max_urls", m.GetMaxUrls())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("respect_robots", m.GetRespectRobots())
        if err != nil {
            return err
        }
    }
    if m.GetRoutingMode() != nil {
        cast := (*m.GetRoutingMode()).String()
        err := writer.WriteStringValue("routing_mode", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("scorer", m.GetScorer())
        if err != nil {
            return err
        }
    }
    if m.GetSeedUrls() != nil {
        err := writer.WriteCollectionOfStringValues("seed_urls", m.GetSeedUrls())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("strategy", m.GetStrategy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("stream", m.GetStream())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("timeout_s", m.GetTimeoutS())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("wait_until", m.GetWaitUntil())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("webhook_url", m.GetWebhookUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DeepCrawlBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFilters sets the filters property value. The filters property
func (m *DeepCrawlBody) SetFilters(value []FilterSpecable)() {
    m.filters = value
}
// SetIncludeSitemaps sets the include_sitemaps property value. The include_sitemaps property
func (m *DeepCrawlBody) SetIncludeSitemaps(value *bool)() {
    m.include_sitemaps = value
}
// SetMaxDepth sets the max_depth property value. The max_depth property
func (m *DeepCrawlBody) SetMaxDepth(value *int32)() {
    m.max_depth = value
}
// SetMaxUrls sets the max_urls property value. The max_urls property
func (m *DeepCrawlBody) SetMaxUrls(value *int32)() {
    m.max_urls = value
}
// SetRespectRobots sets the respect_robots property value. The respect_robots property
func (m *DeepCrawlBody) SetRespectRobots(value *bool)() {
    m.respect_robots = value
}
// SetRoutingMode sets the routing_mode property value. Routing mode. auto (default) = we pick the cheapest network that succeeds and automatically escalate on a block. standard = normal targets only. premium = always use our premium network. Most callers should leave this at auto.
func (m *DeepCrawlBody) SetRoutingMode(value *DeepCrawlBody_routing_mode)() {
    m.routing_mode = value
}
// SetScorer sets the scorer property value. The scorer property
func (m *DeepCrawlBody) SetScorer(value ScorerSpecable)() {
    m.scorer = value
}
// SetSeedUrls sets the seed_urls property value. The seed_urls property
func (m *DeepCrawlBody) SetSeedUrls(value []string)() {
    m.seed_urls = value
}
// SetStrategy sets the strategy property value. The strategy property
func (m *DeepCrawlBody) SetStrategy(value *string)() {
    m.strategy = value
}
// SetStream sets the stream property value. The stream property
func (m *DeepCrawlBody) SetStream(value *bool)() {
    m.stream = value
}
// SetTimeoutS sets the timeout_s property value. The timeout_s property
func (m *DeepCrawlBody) SetTimeoutS(value DeepCrawlBody_DeepCrawlBody_timeout_sable)() {
    m.timeout_s = value
}
// SetWaitUntil sets the wait_until property value. The wait_until property
func (m *DeepCrawlBody) SetWaitUntil(value DeepCrawlBody_DeepCrawlBody_wait_untilable)() {
    m.wait_until = value
}
// SetWebhookUrl sets the webhook_url property value. The webhook_url property
func (m *DeepCrawlBody) SetWebhookUrl(value DeepCrawlBody_DeepCrawlBody_webhook_urlable)() {
    m.webhook_url = value
}
type DeepCrawlBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFilters()([]FilterSpecable)
    GetIncludeSitemaps()(*bool)
    GetMaxDepth()(*int32)
    GetMaxUrls()(*int32)
    GetRespectRobots()(*bool)
    GetRoutingMode()(*DeepCrawlBody_routing_mode)
    GetScorer()(ScorerSpecable)
    GetSeedUrls()([]string)
    GetStrategy()(*string)
    GetStream()(*bool)
    GetTimeoutS()(DeepCrawlBody_DeepCrawlBody_timeout_sable)
    GetWaitUntil()(DeepCrawlBody_DeepCrawlBody_wait_untilable)
    GetWebhookUrl()(DeepCrawlBody_DeepCrawlBody_webhook_urlable)
    SetFilters(value []FilterSpecable)()
    SetIncludeSitemaps(value *bool)()
    SetMaxDepth(value *int32)()
    SetMaxUrls(value *int32)()
    SetRespectRobots(value *bool)()
    SetRoutingMode(value *DeepCrawlBody_routing_mode)()
    SetScorer(value ScorerSpecable)()
    SetSeedUrls(value []string)()
    SetStrategy(value *string)()
    SetStream(value *bool)()
    SetTimeoutS(value DeepCrawlBody_DeepCrawlBody_timeout_sable)()
    SetWaitUntil(value DeepCrawlBody_DeepCrawlBody_wait_untilable)()
    SetWebhookUrl(value DeepCrawlBody_DeepCrawlBody_webhook_urlable)()
}
