// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// ProblemDetails returned on a non-2xx response when the request could not be completed on our side (authentication, rate limiting, capacity, render timeout, …). Sent with the `application/problem+json` media type (RFC 9457).
type ProblemDetails struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ApiError
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The stable, machine-readable error code.
    code *ErrorCode
    // A human-readable explanation specific to this occurrence.
    detail *string
    // The request identifier for this occurrence (the same value as the `X-Request-Id` response header). Quote it when contacting support.
    instance *string
    // Suggested number of seconds to wait before retrying. Present only on retryable codes; mirrors the `Retry-After` response header when set.
    retry_after *int32
    // Whether retrying the same call (after a short backoff) can succeed. `false` means the request will keep failing until you change something.
    retryable *bool
    // The HTTP status code for this response.
    status *int32
    // A short, human-readable summary of the error type.
    title *string
    // A stable URI that identifies the error type. Dereferences to the matching entry on the public error reference.
    typeEscaped *string
}
// NewProblemDetails instantiates a new ProblemDetails and sets the default values.
func NewProblemDetails()(*ProblemDetails) {
    m := &ProblemDetails{
        ApiError: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewApiError(),
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateProblemDetailsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateProblemDetailsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewProblemDetails(), nil
}
// Error the primary error message.
// returns a string when successful
func (m *ProblemDetails) Error()(string) {
    return m.ApiError.Error()
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ProblemDetails) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCode gets the code property value. The stable, machine-readable error code.
// returns a *ErrorCode when successful
func (m *ProblemDetails) GetCode()(*ErrorCode) {
    return m.code
}
// GetDetail gets the detail property value. A human-readable explanation specific to this occurrence.
// returns a *string when successful
func (m *ProblemDetails) GetDetail()(*string) {
    return m.detail
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ProblemDetails) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["code"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseErrorCode)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCode(val.(*ErrorCode))
        }
        return nil
    }
    res["detail"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDetail(val)
        }
        return nil
    }
    res["instance"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInstance(val)
        }
        return nil
    }
    res["retry_after"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRetryAfter(val)
        }
        return nil
    }
    res["retryable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRetryable(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    res["title"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTitle(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val)
        }
        return nil
    }
    return res
}
// GetInstance gets the instance property value. The request identifier for this occurrence (the same value as the `X-Request-Id` response header). Quote it when contacting support.
// returns a *string when successful
func (m *ProblemDetails) GetInstance()(*string) {
    return m.instance
}
// GetRetryable gets the retryable property value. Whether retrying the same call (after a short backoff) can succeed. `false` means the request will keep failing until you change something.
// returns a *bool when successful
func (m *ProblemDetails) GetRetryable()(*bool) {
    return m.retryable
}
// GetRetryAfter gets the retry_after property value. Suggested number of seconds to wait before retrying. Present only on retryable codes; mirrors the `Retry-After` response header when set.
// returns a *int32 when successful
func (m *ProblemDetails) GetRetryAfter()(*int32) {
    return m.retry_after
}
// GetStatus gets the status property value. The HTTP status code for this response.
// returns a *int32 when successful
func (m *ProblemDetails) GetStatus()(*int32) {
    return m.status
}
// GetTitle gets the title property value. A short, human-readable summary of the error type.
// returns a *string when successful
func (m *ProblemDetails) GetTitle()(*string) {
    return m.title
}
// GetTypeEscaped gets the type property value. A stable URI that identifies the error type. Dereferences to the matching entry on the public error reference.
// returns a *string when successful
func (m *ProblemDetails) GetTypeEscaped()(*string) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *ProblemDetails) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCode() != nil {
        cast := (*m.GetCode()).String()
        err := writer.WriteStringValue("code", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("detail", m.GetDetail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("instance", m.GetInstance())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("retryable", m.GetRetryable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("retry_after", m.GetRetryAfter())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("title", m.GetTitle())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("type", m.GetTypeEscaped())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ProblemDetails) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCode sets the code property value. The stable, machine-readable error code.
func (m *ProblemDetails) SetCode(value *ErrorCode)() {
    m.code = value
}
// SetDetail sets the detail property value. A human-readable explanation specific to this occurrence.
func (m *ProblemDetails) SetDetail(value *string)() {
    m.detail = value
}
// SetInstance sets the instance property value. The request identifier for this occurrence (the same value as the `X-Request-Id` response header). Quote it when contacting support.
func (m *ProblemDetails) SetInstance(value *string)() {
    m.instance = value
}
// SetRetryable sets the retryable property value. Whether retrying the same call (after a short backoff) can succeed. `false` means the request will keep failing until you change something.
func (m *ProblemDetails) SetRetryable(value *bool)() {
    m.retryable = value
}
// SetRetryAfter sets the retry_after property value. Suggested number of seconds to wait before retrying. Present only on retryable codes; mirrors the `Retry-After` response header when set.
func (m *ProblemDetails) SetRetryAfter(value *int32)() {
    m.retry_after = value
}
// SetStatus sets the status property value. The HTTP status code for this response.
func (m *ProblemDetails) SetStatus(value *int32)() {
    m.status = value
}
// SetTitle sets the title property value. A short, human-readable summary of the error type.
func (m *ProblemDetails) SetTitle(value *string)() {
    m.title = value
}
// SetTypeEscaped sets the type property value. A stable URI that identifies the error type. Dereferences to the matching entry on the public error reference.
func (m *ProblemDetails) SetTypeEscaped(value *string)() {
    m.typeEscaped = value
}
type ProblemDetailsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCode()(*ErrorCode)
    GetDetail()(*string)
    GetInstance()(*string)
    GetRetryable()(*bool)
    GetRetryAfter()(*int32)
    GetStatus()(*int32)
    GetTitle()(*string)
    GetTypeEscaped()(*string)
    SetCode(value *ErrorCode)()
    SetDetail(value *string)()
    SetInstance(value *string)()
    SetRetryable(value *bool)()
    SetRetryAfter(value *int32)()
    SetStatus(value *int32)()
    SetTitle(value *string)()
    SetTypeEscaped(value *string)()
}
